# Auto-generated building blueprint
NAME = "bp_011"
BLOCKS = [
    ((0, 0, 0), "universal_minecraft:dirt", {}),
    ((0, 0, 1), "universal_minecraft:dirt", {}),
    ((0, 0, 2), "universal_minecraft:dirt", {}),
    ((0, 0, 3), "universal_minecraft:dirt", {}),
    ((0, 0, 4), "universal_minecraft:dirt", {}),
    ((0, 0, 5), "universal_minecraft:dirt", {}),
    ((0, 1, 0), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((0, 1, 1), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((0, 1, 2), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((0, 1, 3), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((0, 1, 4), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((0, 1, 5), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((1, 0, 0), "universal_minecraft:dirt", {}),
    ((1, 0, 1), "universal_minecraft:dirt", {}),
    ((1, 0, 2), "universal_minecraft:dirt", {}),
    ((1, 0, 3), "universal_minecraft:dirt", {}),
    ((1, 0, 4), "universal_minecraft:dirt", {}),
    ((1, 0, 5), "universal_minecraft:dirt", {}),
    ((1, 1, 0), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((1, 1, 1), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((1, 1, 2), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((1, 1, 3), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((1, 1, 4), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((1, 1, 5), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((2, 0, 0), "universal_minecraft:dirt", {}),
    ((2, 0, 1), "universal_minecraft:dirt", {}),
    ((2, 0, 2), "universal_minecraft:dirt", {}),
    ((2, 0, 3), "universal_minecraft:dirt", {}),
    ((2, 0, 4), "universal_minecraft:dirt", {}),
    ((2, 0, 5), "universal_minecraft:dirt", {}),
    ((2, 1, 0), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((2, 1, 1), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((2, 1, 2), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((2, 1, 3), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((2, 1, 4), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((2, 1, 5), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((3, 0, 0), "universal_minecraft:dirt", {}),
    ((3, 0, 1), "universal_minecraft:dirt", {}),
    ((3, 0, 2), "universal_minecraft:dirt", {}),
    ((3, 0, 3), "universal_minecraft:dirt", {}),
    ((3, 0, 4), "universal_minecraft:dirt", {}),
    ((3, 0, 5), "universal_minecraft:dirt", {}),
    ((3, 1, 0), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((3, 1, 1), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((3, 1, 2), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((3, 1, 3), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((3, 1, 4), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((3, 1, 5), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((4, 0, 0), "universal_minecraft:dirt", {}),
    ((4, 0, 1), "universal_minecraft:dirt", {}),
    ((4, 0, 2), "universal_minecraft:dirt", {}),
    ((4, 0, 3), "universal_minecraft:dirt", {}),
    ((4, 0, 4), "universal_minecraft:dirt", {}),
    ((4, 0, 5), "universal_minecraft:dirt", {}),
    ((4, 1, 0), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((4, 1, 1), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((4, 1, 2), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((4, 1, 3), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((4, 1, 4), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((4, 1, 5), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((5, 0, 0), "universal_minecraft:dirt", {}),
    ((5, 0, 1), "universal_minecraft:dirt", {}),
    ((5, 0, 2), "universal_minecraft:dirt", {}),
    ((5, 0, 3), "universal_minecraft:dirt", {}),
    ((5, 0, 4), "universal_minecraft:dirt", {}),
    ((5, 0, 5), "universal_minecraft:dirt", {}),
    ((5, 1, 0), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((5, 1, 1), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((5, 1, 2), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((5, 1, 3), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((5, 1, 4), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((5, 1, 5), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
]
