# Auto-generated building blueprint
NAME = "bp_014"
BLOCKS = [
    ((0, 0, 0), "universal_minecraft:dirt", {}),
    ((0, 0, 1), "universal_minecraft:dirt", {}),
    ((0, 0, 2), "universal_minecraft:dirt", {}),
    ((0, 1, 0), "universal_minecraft:dirt", {}),
    ((0, 1, 1), "universal_minecraft:dirt", {}),
    ((0, 1, 2), "universal_minecraft:dirt", {}),
    ((0, 2, 0), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((0, 2, 1), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((0, 2, 2), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((0, 3, 0), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((0, 3, 1), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((0, 3, 2), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((0, 4, 1), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((0, 4, 2), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((0, 5, 1), "universal_minecraft:log", {'material': StringTag("dark_oak"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((0, 5, 2), "universal_minecraft:log", {'material': StringTag("dark_oak"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((0, 6, 0), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("south"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((0, 6, 1), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((0, 6, 2), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((0, 7, 0), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((0, 7, 1), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((0, 7, 2), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((0, 8, 0), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((0, 8, 1), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((0, 8, 2), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((0, 9, 0), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("east"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((0, 9, 1), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("east"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((0, 9, 2), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("east"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
]
