# Auto-generated building blueprint
NAME = "bp_001"
BLOCKS = [
    ((0, 0, 0), "universal_minecraft:dirt", {}),
    ((0, 0, 1), "universal_minecraft:dirt", {}),
    ((0, 0, 2), "universal_minecraft:dirt", {}),
    ((0, 0, 3), "universal_minecraft:dirt", {}),
    ((0, 0, 4), "universal_minecraft:dirt", {}),
    ((0, 0, 5), "universal_minecraft:dirt", {}),
    ((0, 0, 6), "universal_minecraft:dirt", {}),
    ((0, 0, 7), "universal_minecraft:dirt", {}),
    ((0, 0, 8), "universal_minecraft:dirt", {}),
    ((0, 0, 9), "universal_minecraft:dirt", {}),
    ((0, 0, 10), "universal_minecraft:dirt", {}),
    ((0, 0, 11), "universal_minecraft:dirt", {}),
    ((0, 0, 12), "universal_minecraft:dirt", {}),
    ((0, 1, 0), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((0, 1, 1), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((0, 1, 2), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((0, 1, 3), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((0, 1, 4), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((0, 1, 5), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((0, 1, 6), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((0, 1, 7), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((0, 1, 8), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((0, 1, 9), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((0, 1, 10), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((0, 1, 11), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((0, 1, 12), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((0, 12, 6), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("east"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((1, 0, 0), "universal_minecraft:dirt", {}),
    ((1, 0, 1), "universal_minecraft:dirt", {}),
    ((1, 0, 2), "universal_minecraft:dirt", {}),
    ((1, 0, 3), "universal_minecraft:dirt", {}),
    ((1, 0, 4), "universal_minecraft:dirt", {}),
    ((1, 0, 5), "universal_minecraft:dirt", {}),
    ((1, 0, 6), "universal_minecraft:dirt", {}),
    ((1, 0, 7), "universal_minecraft:dirt", {}),
    ((1, 0, 8), "universal_minecraft:dirt", {}),
    ((1, 0, 9), "universal_minecraft:dirt", {}),
    ((1, 0, 10), "universal_minecraft:dirt", {}),
    ((1, 0, 11), "universal_minecraft:dirt", {}),
    ((1, 0, 12), "universal_minecraft:dirt", {}),
    ((1, 1, 0), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((1, 1, 1), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((1, 1, 2), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((1, 1, 3), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((1, 1, 4), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((1, 1, 5), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((1, 1, 6), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((1, 1, 7), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((1, 1, 8), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((1, 1, 9), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((1, 1, 10), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((1, 1, 11), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((1, 1, 12), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((1, 7, 0), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((1, 7, 1), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((1, 7, 11), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((1, 7, 12), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((1, 8, 1), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((1, 8, 2), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((1, 8, 10), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((1, 8, 11), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((1, 9, 2), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((1, 9, 3), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((1, 9, 9), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((1, 9, 10), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((1, 10, 3), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((1, 10, 8), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((1, 10, 9), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((1, 11, 4), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((1, 11, 5), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((1, 11, 6), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((1, 11, 7), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((1, 11, 8), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((1, 12, 6), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("west"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((2, 0, 0), "universal_minecraft:dirt", {}),
    ((2, 0, 1), "universal_minecraft:dirt", {}),
    ((2, 0, 2), "universal_minecraft:dirt", {}),
    ((2, 0, 3), "universal_minecraft:dirt", {}),
    ((2, 0, 4), "universal_minecraft:dirt", {}),
    ((2, 0, 5), "universal_minecraft:dirt", {}),
    ((2, 0, 6), "universal_minecraft:dirt", {}),
    ((2, 0, 7), "universal_minecraft:dirt", {}),
    ((2, 0, 8), "universal_minecraft:dirt", {}),
    ((2, 0, 9), "universal_minecraft:dirt", {}),
    ((2, 0, 10), "universal_minecraft:dirt", {}),
    ((2, 0, 11), "universal_minecraft:dirt", {}),
    ((2, 0, 12), "universal_minecraft:dirt", {}),
    ((2, 1, 0), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((2, 1, 1), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((2, 1, 2), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((2, 1, 3), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((2, 1, 4), "universal_minecraft:dirt", {}),
    ((2, 1, 5), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((2, 1, 6), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((2, 1, 7), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((2, 1, 8), "universal_minecraft:dirt", {}),
    ((2, 1, 9), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((2, 1, 10), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((2, 1, 11), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((2, 1, 12), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((2, 2, 4), "universal_minecraft:stone_bricks", {'variant': StringTag("chiseled")}),
    ((2, 2, 8), "universal_minecraft:stone_bricks", {'variant': StringTag("chiseled")}),
    ((2, 3, 4), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((2, 3, 8), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((2, 4, 4), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((2, 4, 8), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((2, 5, 4), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((2, 5, 8), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((2, 6, 3), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((2, 6, 4), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((2, 6, 5), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((2, 6, 7), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((2, 6, 8), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((2, 6, 9), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((2, 7, 0), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((2, 7, 1), "universal_minecraft:planks", {'material': StringTag("dark_oak")}),
    ((2, 7, 2), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((2, 7, 3), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((2, 7, 4), "universal_minecraft:stone_bricks", {'variant': StringTag("chiseled")}),
    ((2, 7, 5), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((2, 7, 6), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((2, 7, 7), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((2, 7, 8), "universal_minecraft:stone_bricks", {'variant': StringTag("chiseled")}),
    ((2, 7, 9), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((2, 7, 10), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((2, 7, 11), "universal_minecraft:planks", {'material': StringTag("dark_oak")}),
    ((2, 7, 12), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((2, 8, 1), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((2, 8, 2), "universal_minecraft:planks", {'material': StringTag("dark_oak")}),
    ((2, 8, 3), "universal_minecraft:planks", {'material': StringTag("dark_oak")}),
    ((2, 8, 4), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((2, 8, 5), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((2, 8, 6), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((2, 8, 7), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((2, 8, 8), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((2, 8, 9), "universal_minecraft:planks", {'material': StringTag("dark_oak")}),
    ((2, 8, 10), "universal_minecraft:planks", {'material': StringTag("dark_oak")}),
    ((2, 8, 11), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((2, 9, 2), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((2, 9, 3), "universal_minecraft:planks", {'material': StringTag("dark_oak")}),
    ((2, 9, 4), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((2, 9, 5), "universal_minecraft:planks", {'material': StringTag("dark_oak")}),
    ((2, 9, 6), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((2, 9, 7), "universal_minecraft:planks", {'material': StringTag("dark_oak")}),
    ((2, 9, 8), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((2, 9, 9), "universal_minecraft:planks", {'material': StringTag("dark_oak")}),
    ((2, 9, 10), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((2, 10, 3), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((2, 10, 4), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((2, 10, 5), "universal_minecraft:planks", {'material': StringTag("dark_oak")}),
    ((2, 10, 6), "universal_minecraft:planks", {'material': StringTag("dark_oak")}),
    ((2, 10, 7), "universal_minecraft:planks", {'material': StringTag("dark_oak")}),
    ((2, 10, 8), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((2, 10, 9), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((2, 11, 4), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((2, 11, 5), "universal_minecraft:planks", {'material': StringTag("dark_oak")}),
    ((2, 11, 6), "universal_minecraft:planks", {'material': StringTag("dark_oak")}),
    ((2, 11, 7), "universal_minecraft:planks", {'material': StringTag("dark_oak")}),
    ((2, 11, 8), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((2, 12, 6), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("bottom")}),
    ((3, 0, 0), "universal_minecraft:dirt", {}),
    ((3, 0, 1), "universal_minecraft:dirt", {}),
    ((3, 0, 2), "universal_minecraft:dirt", {}),
    ((3, 0, 3), "universal_minecraft:dirt", {}),
    ((3, 0, 4), "universal_minecraft:dirt", {}),
    ((3, 0, 5), "universal_minecraft:dirt", {}),
    ((3, 0, 6), "universal_minecraft:dirt", {}),
    ((3, 0, 7), "universal_minecraft:dirt", {}),
    ((3, 0, 8), "universal_minecraft:dirt", {}),
    ((3, 0, 9), "universal_minecraft:dirt", {}),
    ((3, 0, 10), "universal_minecraft:dirt", {}),
    ((3, 0, 11), "universal_minecraft:dirt", {}),
    ((3, 0, 12), "universal_minecraft:dirt", {}),
    ((3, 1, 0), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((3, 1, 1), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((3, 1, 2), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((3, 1, 3), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((3, 1, 4), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((3, 1, 5), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((3, 1, 6), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((3, 1, 7), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((3, 1, 8), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((3, 1, 9), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((3, 1, 10), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((3, 1, 11), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((3, 1, 12), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((3, 2, 3), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("east"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((3, 2, 4), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((3, 2, 5), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("east"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((3, 2, 6), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("east"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((3, 2, 7), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("east"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((3, 2, 8), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((3, 2, 9), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("east"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((3, 3, 3), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((3, 3, 4), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((3, 3, 5), "universal_minecraft:glass_pane", {'east': StringTag("false"), 'north': StringTag("true"), 'south': StringTag("true"), 'west': StringTag("false")}),
    ((3, 3, 6), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((3, 3, 7), "universal_minecraft:glass_pane", {'east': StringTag("false"), 'north': StringTag("true"), 'south': StringTag("true"), 'west': StringTag("false")}),
    ((3, 3, 8), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((3, 3, 9), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((3, 4, 3), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((3, 4, 4), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((3, 4, 5), "universal_minecraft:glass_pane", {'east': StringTag("false"), 'north': StringTag("true"), 'south': StringTag("true"), 'west': StringTag("false")}),
    ((3, 4, 6), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((3, 4, 7), "universal_minecraft:glass_pane", {'east': StringTag("false"), 'north': StringTag("true"), 'south': StringTag("true"), 'west': StringTag("false")}),
    ((3, 4, 8), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((3, 4, 9), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((3, 5, 3), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((3, 5, 4), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((3, 5, 5), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((3, 5, 6), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((3, 5, 7), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((3, 5, 8), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((3, 5, 9), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((3, 6, 2), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("east"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((3, 6, 3), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((3, 6, 4), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((3, 6, 5), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((3, 6, 6), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((3, 6, 7), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((3, 6, 8), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((3, 6, 9), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((3, 6, 10), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("east"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((3, 7, 0), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((3, 7, 1), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((3, 7, 2), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((3, 7, 3), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((3, 7, 4), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((3, 7, 5), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("west"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((3, 7, 6), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("x"), 'stripped': StringTag("false")}),
    ((3, 7, 7), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("west"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((3, 7, 8), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((3, 7, 9), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((3, 7, 10), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((3, 7, 11), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((3, 7, 12), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((3, 8, 1), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((3, 8, 6), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("west"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((3, 8, 11), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((3, 9, 2), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((3, 9, 10), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((3, 10, 3), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((3, 10, 9), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((3, 11, 4), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((3, 11, 5), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((3, 11, 6), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((3, 11, 7), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((3, 11, 8), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((3, 12, 6), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("bottom")}),
    ((4, 0, 0), "universal_minecraft:dirt", {}),
    ((4, 0, 1), "universal_minecraft:dirt", {}),
    ((4, 0, 2), "universal_minecraft:dirt", {}),
    ((4, 0, 3), "universal_minecraft:dirt", {}),
    ((4, 0, 4), "universal_minecraft:dirt", {}),
    ((4, 0, 5), "universal_minecraft:dirt", {}),
    ((4, 0, 6), "universal_minecraft:dirt", {}),
    ((4, 0, 7), "universal_minecraft:dirt", {}),
    ((4, 0, 8), "universal_minecraft:dirt", {}),
    ((4, 0, 9), "universal_minecraft:dirt", {}),
    ((4, 0, 10), "universal_minecraft:dirt", {}),
    ((4, 0, 11), "universal_minecraft:dirt", {}),
    ((4, 0, 12), "universal_minecraft:dirt", {}),
    ((4, 1, 0), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((4, 1, 1), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((4, 1, 2), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((4, 1, 3), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((4, 1, 4), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((4, 1, 5), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((4, 1, 6), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((4, 1, 7), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((4, 1, 8), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((4, 1, 9), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((4, 1, 10), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((4, 1, 11), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((4, 1, 12), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((4, 2, 2), "universal_minecraft:stone_bricks", {'variant': StringTag("chiseled")}),
    ((4, 2, 10), "universal_minecraft:stone_bricks", {'variant': StringTag("chiseled")}),
    ((4, 3, 2), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((4, 3, 10), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((4, 4, 2), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((4, 4, 10), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((4, 5, 2), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((4, 5, 10), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((4, 6, 1), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("south"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((4, 6, 2), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((4, 6, 10), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((4, 6, 11), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("north"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((4, 7, 0), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((4, 7, 1), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((4, 7, 2), "universal_minecraft:stone_bricks", {'variant': StringTag("chiseled")}),
    ((4, 7, 6), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("x"), 'stripped': StringTag("false")}),
    ((4, 7, 10), "universal_minecraft:stone_bricks", {'variant': StringTag("chiseled")}),
    ((4, 7, 11), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((4, 7, 12), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((4, 8, 1), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((4, 8, 2), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((4, 8, 10), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((4, 8, 11), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((4, 9, 2), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((4, 9, 10), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((4, 10, 3), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((4, 10, 9), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((4, 11, 4), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((4, 11, 5), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((4, 11, 6), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((4, 11, 7), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((4, 11, 8), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((4, 12, 6), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("bottom")}),
    ((5, 0, 0), "universal_minecraft:dirt", {}),
    ((5, 0, 1), "universal_minecraft:dirt", {}),
    ((5, 0, 2), "universal_minecraft:dirt", {}),
    ((5, 0, 3), "universal_minecraft:dirt", {}),
    ((5, 0, 4), "universal_minecraft:dirt", {}),
    ((5, 0, 5), "universal_minecraft:dirt", {}),
    ((5, 0, 6), "universal_minecraft:dirt", {}),
    ((5, 0, 7), "universal_minecraft:dirt", {}),
    ((5, 0, 8), "universal_minecraft:dirt", {}),
    ((5, 0, 9), "universal_minecraft:dirt", {}),
    ((5, 0, 10), "universal_minecraft:dirt", {}),
    ((5, 0, 11), "universal_minecraft:dirt", {}),
    ((5, 0, 12), "universal_minecraft:dirt", {}),
    ((5, 1, 0), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((5, 1, 1), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((5, 1, 2), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((5, 1, 3), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((5, 1, 4), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((5, 1, 5), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((5, 1, 6), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((5, 1, 7), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((5, 1, 8), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((5, 1, 9), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((5, 1, 10), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((5, 1, 11), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((5, 1, 12), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((5, 2, 1), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("south"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((5, 2, 11), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("north"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((5, 3, 1), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((5, 3, 11), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((5, 4, 1), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((5, 4, 10), "universal_minecraft:fence", {'material': StringTag("oak"), 'east': StringTag("false"), 'north': StringTag("false"), 'south': StringTag("true"), 'west': StringTag("true")}),
    ((5, 4, 11), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((5, 5, 1), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((5, 5, 10), "universal_minecraft:torch", {'facing': StringTag("up")}),
    ((5, 5, 11), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((5, 6, 0), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((5, 6, 1), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((5, 6, 11), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((5, 6, 12), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((5, 7, 0), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((5, 7, 1), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((5, 7, 6), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("x"), 'stripped': StringTag("false")}),
    ((5, 7, 11), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((5, 7, 12), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((5, 8, 1), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((5, 8, 11), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((5, 9, 2), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((5, 9, 10), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((5, 10, 3), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((5, 10, 9), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((5, 11, 4), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((5, 11, 5), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((5, 11, 6), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((5, 11, 7), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((5, 11, 8), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((5, 12, 6), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("bottom")}),
    ((6, 0, 0), "universal_minecraft:dirt", {}),
    ((6, 0, 1), "universal_minecraft:dirt", {}),
    ((6, 0, 2), "universal_minecraft:dirt", {}),
    ((6, 0, 3), "universal_minecraft:dirt", {}),
    ((6, 0, 4), "universal_minecraft:dirt", {}),
    ((6, 0, 5), "universal_minecraft:dirt", {}),
    ((6, 0, 6), "universal_minecraft:dirt", {}),
    ((6, 0, 7), "universal_minecraft:dirt", {}),
    ((6, 0, 8), "universal_minecraft:dirt", {}),
    ((6, 0, 9), "universal_minecraft:dirt", {}),
    ((6, 0, 10), "universal_minecraft:dirt", {}),
    ((6, 0, 11), "universal_minecraft:dirt", {}),
    ((6, 0, 12), "universal_minecraft:dirt", {}),
    ((6, 1, 0), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((6, 1, 1), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((6, 1, 2), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((6, 1, 3), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((6, 1, 4), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((6, 1, 5), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((6, 1, 6), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((6, 1, 7), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((6, 1, 8), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((6, 1, 9), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((6, 1, 10), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((6, 1, 11), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((6, 1, 12), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((6, 2, 1), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("south"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((6, 2, 11), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("north"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((6, 3, 1), "universal_minecraft:glass_pane", {'east': StringTag("true"), 'north': StringTag("false"), 'south': StringTag("false"), 'west': StringTag("true")}),
    ((6, 3, 11), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((6, 4, 1), "universal_minecraft:glass_pane", {'east': StringTag("true"), 'north': StringTag("false"), 'south': StringTag("false"), 'west': StringTag("true")}),
    ((6, 4, 11), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((6, 5, 1), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((6, 5, 11), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((6, 6, 1), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((6, 6, 11), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((6, 7, 0), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((6, 7, 1), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((6, 7, 6), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("x"), 'stripped': StringTag("false")}),
    ((6, 7, 11), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((6, 7, 12), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((6, 8, 1), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((6, 8, 11), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((6, 9, 2), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((6, 9, 10), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((6, 10, 3), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((6, 10, 9), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((6, 11, 4), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((6, 11, 5), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((6, 11, 6), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((6, 11, 7), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((6, 11, 8), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((6, 12, 6), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("bottom")}),
    ((7, 0, 0), "universal_minecraft:dirt", {}),
    ((7, 0, 1), "universal_minecraft:dirt", {}),
    ((7, 0, 2), "universal_minecraft:dirt", {}),
    ((7, 0, 3), "universal_minecraft:dirt", {}),
    ((7, 0, 4), "universal_minecraft:dirt", {}),
    ((7, 0, 5), "universal_minecraft:dirt", {}),
    ((7, 0, 6), "universal_minecraft:dirt", {}),
    ((7, 0, 7), "universal_minecraft:dirt", {}),
    ((7, 0, 8), "universal_minecraft:dirt", {}),
    ((7, 0, 9), "universal_minecraft:dirt", {}),
    ((7, 0, 10), "universal_minecraft:dirt", {}),
    ((7, 0, 11), "universal_minecraft:dirt", {}),
    ((7, 0, 12), "universal_minecraft:dirt", {}),
    ((7, 1, 0), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((7, 1, 1), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((7, 1, 2), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((7, 1, 3), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((7, 1, 4), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((7, 1, 5), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((7, 1, 6), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((7, 1, 7), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((7, 1, 8), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((7, 1, 9), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((7, 1, 10), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((7, 1, 11), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((7, 1, 12), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((7, 2, 1), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("south"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((7, 2, 11), "universal_minecraft:door", {'material': StringTag("oak"), 'facing': StringTag("south"), 'half': StringTag("lower"), 'hinge': StringTag("left"), 'open': StringTag("false"), 'powered': StringTag("false")}),
    ((7, 3, 1), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((7, 3, 11), "universal_minecraft:door", {'material': StringTag("oak"), 'facing': StringTag("south"), 'half': StringTag("upper"), 'hinge': StringTag("left"), 'open': StringTag("false"), 'powered': StringTag("false")}),
    ((7, 4, 1), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((7, 4, 11), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((7, 5, 1), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((7, 5, 11), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((7, 6, 1), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((7, 6, 11), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((7, 7, 0), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((7, 7, 1), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((7, 7, 2), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("z"), 'stripped': StringTag("false")}),
    ((7, 7, 3), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("z"), 'stripped': StringTag("false")}),
    ((7, 7, 4), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("z"), 'stripped': StringTag("false")}),
    ((7, 7, 5), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("z"), 'stripped': StringTag("false")}),
    ((7, 7, 6), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("z"), 'stripped': StringTag("false")}),
    ((7, 7, 7), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("z"), 'stripped': StringTag("false")}),
    ((7, 7, 8), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("z"), 'stripped': StringTag("false")}),
    ((7, 7, 9), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("z"), 'stripped': StringTag("false")}),
    ((7, 7, 10), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("z"), 'stripped': StringTag("false")}),
    ((7, 7, 11), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((7, 7, 12), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((7, 8, 1), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((7, 8, 2), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((7, 8, 6), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((7, 8, 10), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((7, 8, 11), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((7, 9, 2), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((7, 9, 6), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((7, 9, 10), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((7, 10, 3), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((7, 10, 6), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((7, 10, 9), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((7, 11, 4), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((7, 11, 5), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((7, 11, 6), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("double")}),
    ((7, 11, 7), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((7, 11, 8), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((7, 12, 6), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("bottom")}),
    ((8, 0, 0), "universal_minecraft:dirt", {}),
    ((8, 0, 1), "universal_minecraft:dirt", {}),
    ((8, 0, 2), "universal_minecraft:dirt", {}),
    ((8, 0, 3), "universal_minecraft:dirt", {}),
    ((8, 0, 4), "universal_minecraft:dirt", {}),
    ((8, 0, 5), "universal_minecraft:dirt", {}),
    ((8, 0, 6), "universal_minecraft:dirt", {}),
    ((8, 0, 7), "universal_minecraft:dirt", {}),
    ((8, 0, 8), "universal_minecraft:dirt", {}),
    ((8, 0, 9), "universal_minecraft:dirt", {}),
    ((8, 0, 10), "universal_minecraft:dirt", {}),
    ((8, 0, 11), "universal_minecraft:dirt", {}),
    ((8, 0, 12), "universal_minecraft:dirt", {}),
    ((8, 1, 0), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((8, 1, 1), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((8, 1, 2), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((8, 1, 3), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((8, 1, 4), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((8, 1, 5), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((8, 1, 6), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((8, 1, 7), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((8, 1, 8), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((8, 1, 9), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((8, 1, 10), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((8, 1, 11), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((8, 1, 12), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((8, 2, 1), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("south"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((8, 2, 11), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("north"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((8, 3, 1), "universal_minecraft:glass_pane", {'east': StringTag("true"), 'north': StringTag("false"), 'south': StringTag("false"), 'west': StringTag("true")}),
    ((8, 3, 11), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((8, 4, 1), "universal_minecraft:glass_pane", {'east': StringTag("true"), 'north': StringTag("false"), 'south': StringTag("false"), 'west': StringTag("true")}),
    ((8, 4, 11), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((8, 5, 1), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((8, 5, 11), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((8, 6, 1), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((8, 6, 11), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((8, 7, 0), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((8, 7, 1), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((8, 7, 6), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("x"), 'stripped': StringTag("false")}),
    ((8, 7, 11), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((8, 7, 12), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((8, 8, 1), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((8, 8, 11), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((8, 9, 2), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((8, 9, 10), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((8, 10, 3), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((8, 10, 9), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((8, 11, 4), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((8, 11, 5), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((8, 11, 6), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((8, 11, 7), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((8, 11, 8), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((8, 12, 6), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("bottom")}),
    ((9, 0, 0), "universal_minecraft:dirt", {}),
    ((9, 0, 1), "universal_minecraft:dirt", {}),
    ((9, 0, 2), "universal_minecraft:dirt", {}),
    ((9, 0, 3), "universal_minecraft:dirt", {}),
    ((9, 0, 4), "universal_minecraft:dirt", {}),
    ((9, 0, 5), "universal_minecraft:dirt", {}),
    ((9, 0, 6), "universal_minecraft:dirt", {}),
    ((9, 0, 7), "universal_minecraft:dirt", {}),
    ((9, 0, 8), "universal_minecraft:dirt", {}),
    ((9, 0, 9), "universal_minecraft:dirt", {}),
    ((9, 0, 10), "universal_minecraft:dirt", {}),
    ((9, 0, 11), "universal_minecraft:dirt", {}),
    ((9, 0, 12), "universal_minecraft:dirt", {}),
    ((9, 1, 0), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((9, 1, 1), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((9, 1, 2), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((9, 1, 3), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((9, 1, 4), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((9, 1, 5), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((9, 1, 6), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((9, 1, 7), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((9, 1, 8), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((9, 1, 9), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((9, 1, 10), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((9, 1, 11), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((9, 1, 12), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((9, 2, 1), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("south"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((9, 2, 11), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("north"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((9, 3, 1), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((9, 3, 11), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((9, 4, 1), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((9, 4, 10), "universal_minecraft:fence", {'material': StringTag("oak"), 'east': StringTag("true"), 'north': StringTag("false"), 'south': StringTag("true"), 'west': StringTag("false")}),
    ((9, 4, 11), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((9, 5, 1), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((9, 5, 10), "universal_minecraft:torch", {'facing': StringTag("up")}),
    ((9, 5, 11), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((9, 6, 0), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((9, 6, 1), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((9, 6, 11), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((9, 6, 12), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((9, 7, 0), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((9, 7, 1), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((9, 7, 6), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("x"), 'stripped': StringTag("false")}),
    ((9, 7, 11), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((9, 7, 12), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((9, 8, 1), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((9, 8, 11), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((9, 9, 2), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((9, 9, 10), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((9, 10, 3), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((9, 10, 9), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((9, 11, 4), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((9, 11, 5), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((9, 11, 6), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((9, 11, 7), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((9, 11, 8), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((9, 12, 6), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("bottom")}),
    ((10, 0, 0), "universal_minecraft:dirt", {}),
    ((10, 0, 1), "universal_minecraft:dirt", {}),
    ((10, 0, 2), "universal_minecraft:dirt", {}),
    ((10, 0, 3), "universal_minecraft:dirt", {}),
    ((10, 0, 4), "universal_minecraft:dirt", {}),
    ((10, 0, 5), "universal_minecraft:dirt", {}),
    ((10, 0, 6), "universal_minecraft:dirt", {}),
    ((10, 0, 7), "universal_minecraft:dirt", {}),
    ((10, 0, 8), "universal_minecraft:dirt", {}),
    ((10, 0, 9), "universal_minecraft:dirt", {}),
    ((10, 0, 10), "universal_minecraft:dirt", {}),
    ((10, 0, 11), "universal_minecraft:dirt", {}),
    ((10, 0, 12), "universal_minecraft:dirt", {}),
    ((10, 1, 0), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((10, 1, 1), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((10, 1, 2), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((10, 1, 3), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((10, 1, 4), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((10, 1, 5), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((10, 1, 6), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((10, 1, 7), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((10, 1, 8), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((10, 1, 9), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((10, 1, 10), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((10, 1, 11), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((10, 1, 12), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((10, 2, 2), "universal_minecraft:stone_bricks", {'variant': StringTag("chiseled")}),
    ((10, 2, 10), "universal_minecraft:stone_bricks", {'variant': StringTag("chiseled")}),
    ((10, 3, 2), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((10, 3, 10), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((10, 4, 2), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((10, 4, 10), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((10, 5, 2), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((10, 5, 10), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((10, 6, 1), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("south"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((10, 6, 2), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((10, 6, 10), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((10, 6, 11), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("north"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((10, 7, 0), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((10, 7, 1), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((10, 7, 2), "universal_minecraft:stone_bricks", {'variant': StringTag("chiseled")}),
    ((10, 7, 6), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("x"), 'stripped': StringTag("false")}),
    ((10, 7, 10), "universal_minecraft:stone_bricks", {'variant': StringTag("chiseled")}),
    ((10, 7, 11), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((10, 7, 12), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((10, 8, 1), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((10, 8, 2), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((10, 8, 10), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((10, 8, 11), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((10, 9, 2), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((10, 9, 10), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((10, 10, 3), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((10, 10, 9), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((10, 11, 4), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((10, 11, 5), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((10, 11, 6), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((10, 11, 7), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((10, 11, 8), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((10, 12, 6), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("bottom")}),
    ((11, 0, 0), "universal_minecraft:dirt", {}),
    ((11, 0, 1), "universal_minecraft:dirt", {}),
    ((11, 0, 2), "universal_minecraft:dirt", {}),
    ((11, 0, 3), "universal_minecraft:dirt", {}),
    ((11, 0, 4), "universal_minecraft:dirt", {}),
    ((11, 0, 5), "universal_minecraft:dirt", {}),
    ((11, 0, 6), "universal_minecraft:dirt", {}),
    ((11, 0, 7), "universal_minecraft:dirt", {}),
    ((11, 0, 8), "universal_minecraft:dirt", {}),
    ((11, 0, 9), "universal_minecraft:dirt", {}),
    ((11, 0, 10), "universal_minecraft:dirt", {}),
    ((11, 0, 11), "universal_minecraft:dirt", {}),
    ((11, 0, 12), "universal_minecraft:dirt", {}),
    ((11, 1, 0), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((11, 1, 1), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((11, 1, 2), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((11, 1, 3), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((11, 1, 4), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((11, 1, 5), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((11, 1, 6), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((11, 1, 7), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((11, 1, 8), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((11, 1, 9), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((11, 1, 10), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((11, 1, 11), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((11, 1, 12), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((11, 2, 3), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("west"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((11, 2, 4), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((11, 2, 5), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("west"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((11, 2, 6), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("west"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((11, 2, 7), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("west"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((11, 2, 8), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((11, 2, 9), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("west"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((11, 3, 3), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((11, 3, 4), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((11, 3, 5), "universal_minecraft:glass_pane", {'east': StringTag("false"), 'north': StringTag("true"), 'south': StringTag("true"), 'west': StringTag("false")}),
    ((11, 3, 6), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((11, 3, 7), "universal_minecraft:glass_pane", {'east': StringTag("false"), 'north': StringTag("true"), 'south': StringTag("true"), 'west': StringTag("false")}),
    ((11, 3, 8), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((11, 3, 9), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((11, 4, 3), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((11, 4, 4), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((11, 4, 5), "universal_minecraft:glass_pane", {'east': StringTag("false"), 'north': StringTag("true"), 'south': StringTag("true"), 'west': StringTag("false")}),
    ((11, 4, 6), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((11, 4, 7), "universal_minecraft:glass_pane", {'east': StringTag("false"), 'north': StringTag("true"), 'south': StringTag("true"), 'west': StringTag("false")}),
    ((11, 4, 8), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((11, 4, 9), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((11, 5, 3), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((11, 5, 4), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((11, 5, 5), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((11, 5, 6), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((11, 5, 7), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((11, 5, 8), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((11, 5, 9), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((11, 6, 2), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("west"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((11, 6, 3), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((11, 6, 4), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((11, 6, 5), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((11, 6, 6), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((11, 6, 7), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((11, 6, 8), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((11, 6, 9), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((11, 6, 10), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("west"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((11, 7, 0), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((11, 7, 1), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((11, 7, 2), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((11, 7, 3), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((11, 7, 4), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((11, 7, 5), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("east"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((11, 7, 6), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("x"), 'stripped': StringTag("false")}),
    ((11, 7, 7), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("east"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((11, 7, 8), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((11, 7, 9), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((11, 7, 10), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((11, 7, 11), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((11, 7, 12), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((11, 8, 1), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((11, 8, 6), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("east"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((11, 8, 11), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((11, 9, 2), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((11, 9, 10), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((11, 10, 3), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((11, 10, 9), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((11, 11, 4), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((11, 11, 5), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((11, 11, 6), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((11, 11, 7), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((11, 11, 8), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((11, 12, 6), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("bottom")}),
    ((12, 0, 0), "universal_minecraft:dirt", {}),
    ((12, 0, 1), "universal_minecraft:dirt", {}),
    ((12, 0, 2), "universal_minecraft:dirt", {}),
    ((12, 0, 3), "universal_minecraft:dirt", {}),
    ((12, 0, 4), "universal_minecraft:dirt", {}),
    ((12, 0, 5), "universal_minecraft:dirt", {}),
    ((12, 0, 6), "universal_minecraft:dirt", {}),
    ((12, 0, 7), "universal_minecraft:dirt", {}),
    ((12, 0, 8), "universal_minecraft:dirt", {}),
    ((12, 0, 9), "universal_minecraft:dirt", {}),
    ((12, 0, 10), "universal_minecraft:dirt", {}),
    ((12, 0, 11), "universal_minecraft:dirt", {}),
    ((12, 0, 12), "universal_minecraft:dirt", {}),
    ((12, 1, 0), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((12, 1, 1), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((12, 1, 2), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((12, 1, 3), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((12, 1, 4), "universal_minecraft:dirt", {}),
    ((12, 1, 5), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((12, 1, 6), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((12, 1, 7), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((12, 1, 8), "universal_minecraft:dirt", {}),
    ((12, 1, 9), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((12, 1, 10), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((12, 1, 11), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((12, 1, 12), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((12, 2, 4), "universal_minecraft:stone_bricks", {'variant': StringTag("chiseled")}),
    ((12, 2, 8), "universal_minecraft:stone_bricks", {'variant': StringTag("chiseled")}),
    ((12, 3, 4), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((12, 3, 8), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((12, 4, 4), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((12, 4, 8), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((12, 5, 4), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((12, 5, 8), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((12, 6, 3), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((12, 6, 4), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((12, 6, 5), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((12, 6, 7), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((12, 6, 8), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((12, 6, 9), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((12, 7, 0), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((12, 7, 1), "universal_minecraft:planks", {'material': StringTag("dark_oak")}),
    ((12, 7, 2), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((12, 7, 3), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((12, 7, 4), "universal_minecraft:stone_bricks", {'variant': StringTag("chiseled")}),
    ((12, 7, 5), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((12, 7, 6), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((12, 7, 7), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((12, 7, 8), "universal_minecraft:stone_bricks", {'variant': StringTag("chiseled")}),
    ((12, 7, 9), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((12, 7, 10), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((12, 7, 11), "universal_minecraft:planks", {'material': StringTag("dark_oak")}),
    ((12, 7, 12), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((12, 8, 1), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((12, 8, 2), "universal_minecraft:planks", {'material': StringTag("dark_oak")}),
    ((12, 8, 3), "universal_minecraft:planks", {'material': StringTag("dark_oak")}),
    ((12, 8, 4), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((12, 8, 5), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((12, 8, 6), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((12, 8, 7), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((12, 8, 8), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((12, 8, 9), "universal_minecraft:planks", {'material': StringTag("dark_oak")}),
    ((12, 8, 10), "universal_minecraft:planks", {'material': StringTag("dark_oak")}),
    ((12, 8, 11), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((12, 9, 2), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((12, 9, 3), "universal_minecraft:planks", {'material': StringTag("dark_oak")}),
    ((12, 9, 4), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((12, 9, 5), "universal_minecraft:planks", {'material': StringTag("dark_oak")}),
    ((12, 9, 6), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((12, 9, 7), "universal_minecraft:planks", {'material': StringTag("dark_oak")}),
    ((12, 9, 8), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((12, 9, 9), "universal_minecraft:planks", {'material': StringTag("dark_oak")}),
    ((12, 9, 10), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((12, 10, 3), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((12, 10, 4), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((12, 10, 5), "universal_minecraft:planks", {'material': StringTag("dark_oak")}),
    ((12, 10, 6), "universal_minecraft:planks", {'material': StringTag("dark_oak")}),
    ((12, 10, 7), "universal_minecraft:planks", {'material': StringTag("dark_oak")}),
    ((12, 10, 8), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((12, 10, 9), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((12, 11, 4), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((12, 11, 5), "universal_minecraft:planks", {'material': StringTag("dark_oak")}),
    ((12, 11, 6), "universal_minecraft:planks", {'material': StringTag("dark_oak")}),
    ((12, 11, 7), "universal_minecraft:planks", {'material': StringTag("dark_oak")}),
    ((12, 11, 8), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((12, 12, 6), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("bottom")}),
    ((13, 0, 0), "universal_minecraft:dirt", {}),
    ((13, 0, 1), "universal_minecraft:dirt", {}),
    ((13, 0, 2), "universal_minecraft:dirt", {}),
    ((13, 0, 3), "universal_minecraft:dirt", {}),
    ((13, 0, 4), "universal_minecraft:dirt", {}),
    ((13, 0, 5), "universal_minecraft:dirt", {}),
    ((13, 0, 6), "universal_minecraft:dirt", {}),
    ((13, 0, 7), "universal_minecraft:dirt", {}),
    ((13, 0, 8), "universal_minecraft:dirt", {}),
    ((13, 0, 9), "universal_minecraft:dirt", {}),
    ((13, 0, 10), "universal_minecraft:dirt", {}),
    ((13, 0, 11), "universal_minecraft:dirt", {}),
    ((13, 0, 12), "universal_minecraft:dirt", {}),
    ((13, 1, 0), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((13, 1, 1), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((13, 1, 2), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((13, 1, 3), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((13, 1, 4), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((13, 1, 5), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((13, 1, 6), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((13, 1, 7), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((13, 1, 8), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((13, 1, 9), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((13, 1, 10), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((13, 1, 11), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((13, 1, 12), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((13, 7, 0), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((13, 7, 1), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((13, 7, 11), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((13, 7, 12), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((13, 8, 1), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((13, 8, 2), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((13, 8, 10), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((13, 8, 11), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((13, 9, 2), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((13, 9, 3), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((13, 9, 9), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((13, 9, 10), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((13, 10, 3), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((13, 10, 4), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((13, 10, 8), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((13, 10, 9), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((13, 11, 4), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((13, 11, 5), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((13, 11, 6), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((13, 11, 7), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((13, 11, 8), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((13, 12, 6), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("east"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((14, 0, 0), "universal_minecraft:dirt", {}),
    ((14, 0, 1), "universal_minecraft:dirt", {}),
    ((14, 0, 2), "universal_minecraft:dirt", {}),
    ((14, 0, 3), "universal_minecraft:dirt", {}),
    ((14, 0, 4), "universal_minecraft:dirt", {}),
    ((14, 0, 5), "universal_minecraft:dirt", {}),
    ((14, 0, 6), "universal_minecraft:dirt", {}),
    ((14, 0, 7), "universal_minecraft:dirt", {}),
    ((14, 0, 8), "universal_minecraft:dirt", {}),
    ((14, 0, 9), "universal_minecraft:dirt", {}),
    ((14, 0, 10), "universal_minecraft:dirt", {}),
    ((14, 0, 11), "universal_minecraft:dirt", {}),
    ((14, 0, 12), "universal_minecraft:dirt", {}),
    ((14, 1, 0), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((14, 1, 1), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((14, 1, 2), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((14, 1, 3), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((14, 1, 4), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((14, 1, 5), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((14, 1, 6), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((14, 1, 7), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((14, 1, 8), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((14, 1, 9), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((14, 1, 10), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((14, 1, 11), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((14, 1, 12), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((14, 12, 6), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("west"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
]
