# Auto-generated building blueprint
NAME = "bp_019"
BLOCKS = [
    ((0, 0, 0), "universal_minecraft:dirt", {}),
    ((0, 0, 1), "universal_minecraft:dirt", {}),
    ((0, 0, 2), "universal_minecraft:dirt", {}),
    ((0, 0, 3), "universal_minecraft:dirt", {}),
    ((0, 0, 4), "universal_minecraft:dirt", {}),
    ((0, 0, 5), "universal_minecraft:dirt", {}),
    ((0, 0, 6), "universal_minecraft:dirt", {}),
    ((0, 0, 7), "universal_minecraft:dirt", {}),
    ((0, 0, 8), "universal_minecraft:dirt", {}),
    ((0, 0, 9), "universal_minecraft:dirt", {}),
    ((0, 0, 10), "universal_minecraft:dirt", {}),
    ((0, 0, 11), "universal_minecraft:dirt", {}),
    ((0, 0, 12), "universal_minecraft:dirt", {}),
    ((0, 1, 0), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((0, 1, 1), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((0, 1, 2), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((0, 1, 3), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((0, 1, 4), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((0, 1, 5), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((0, 1, 6), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((0, 1, 7), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((0, 1, 8), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((0, 1, 9), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((0, 1, 10), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((0, 1, 11), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((0, 1, 12), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((1, 0, 0), "universal_minecraft:dirt", {}),
    ((1, 0, 1), "universal_minecraft:dirt", {}),
    ((1, 0, 2), "universal_minecraft:dirt", {}),
    ((1, 0, 3), "universal_minecraft:dirt", {}),
    ((1, 0, 4), "universal_minecraft:dirt", {}),
    ((1, 0, 5), "universal_minecraft:dirt", {}),
    ((1, 0, 6), "universal_minecraft:dirt", {}),
    ((1, 0, 7), "universal_minecraft:dirt", {}),
    ((1, 0, 8), "universal_minecraft:dirt", {}),
    ((1, 0, 9), "universal_minecraft:dirt", {}),
    ((1, 0, 10), "universal_minecraft:dirt", {}),
    ((1, 0, 11), "universal_minecraft:dirt", {}),
    ((1, 0, 12), "universal_minecraft:dirt", {}),
    ((1, 1, 0), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((1, 1, 1), "universal_minecraft:dirt", {}),
    ((1, 1, 2), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((1, 1, 3), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((1, 1, 4), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((1, 1, 5), "universal_minecraft:dirt", {}),
    ((1, 1, 6), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((1, 1, 7), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((1, 1, 8), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((1, 1, 9), "universal_minecraft:dirt", {}),
    ((1, 1, 10), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((1, 1, 11), "universal_minecraft:dirt", {}),
    ((1, 1, 12), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((1, 2, 1), "universal_minecraft:stone_bricks", {'variant': StringTag("chiseled")}),
    ((1, 2, 3), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("east"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((1, 2, 5), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("east"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((1, 2, 7), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("east"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((1, 2, 9), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("east"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((1, 2, 11), "universal_minecraft:stone_bricks", {'variant': StringTag("chiseled")}),
    ((1, 3, 1), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((1, 3, 11), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((1, 4, 1), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((1, 4, 11), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((1, 5, 1), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((1, 5, 2), "universal_minecraft:bars", {'material': StringTag("iron"), 'east': StringTag("true"), 'north': StringTag("true"), 'south': StringTag("false"), 'west': StringTag("false")}),
    ((1, 5, 3), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("east"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((1, 5, 5), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("east"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((1, 5, 7), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("east"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((1, 5, 9), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("east"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((1, 5, 10), "universal_minecraft:bars", {'material': StringTag("iron"), 'east': StringTag("true"), 'north': StringTag("false"), 'south': StringTag("true"), 'west': StringTag("false")}),
    ((1, 5, 11), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((1, 6, 1), "universal_minecraft:stone_bricks", {'variant': StringTag("chiseled")}),
    ((1, 6, 2), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((1, 6, 3), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((1, 6, 4), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((1, 6, 5), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((1, 6, 6), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((1, 6, 7), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((1, 6, 8), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((1, 6, 9), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((1, 6, 10), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((1, 6, 11), "universal_minecraft:stone_bricks", {'variant': StringTag("chiseled")}),
    ((1, 7, 1), "universal_minecraft:wall", {'material': StringTag("cobblestone"), 'east': StringTag("low"), 'north': StringTag("none"), 'south': StringTag("low"), 'up': StringTag("true"), 'west': StringTag("none")}),
    ((1, 7, 2), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((1, 7, 3), "universal_minecraft:bars", {'material': StringTag("iron"), 'east': StringTag("false"), 'north': StringTag("true"), 'south': StringTag("false"), 'west': StringTag("false")}),
    ((1, 7, 5), "universal_minecraft:bars", {'material': StringTag("iron"), 'east': StringTag("false"), 'north': StringTag("false"), 'south': StringTag("true"), 'west': StringTag("false")}),
    ((1, 7, 6), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((1, 7, 7), "universal_minecraft:bars", {'material': StringTag("iron"), 'east': StringTag("false"), 'north': StringTag("true"), 'south': StringTag("false"), 'west': StringTag("false")}),
    ((1, 7, 9), "universal_minecraft:bars", {'material': StringTag("iron"), 'east': StringTag("false"), 'north': StringTag("false"), 'south': StringTag("true"), 'west': StringTag("false")}),
    ((1, 7, 10), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((1, 7, 11), "universal_minecraft:wall", {'material': StringTag("cobblestone"), 'east': StringTag("low"), 'north': StringTag("low"), 'south': StringTag("none"), 'up': StringTag("true"), 'west': StringTag("none")}),
    ((1, 8, 1), "universal_minecraft:wall", {'material': StringTag("cobblestone"), 'east': StringTag("none"), 'north': StringTag("none"), 'south': StringTag("none"), 'up': StringTag("true"), 'west': StringTag("none")}),
    ((1, 8, 11), "universal_minecraft:wall", {'material': StringTag("cobblestone"), 'east': StringTag("none"), 'north': StringTag("none"), 'south': StringTag("none"), 'up': StringTag("true"), 'west': StringTag("none")}),
    ((1, 9, 1), "universal_minecraft:torch", {'facing': StringTag("up")}),
    ((1, 9, 11), "universal_minecraft:torch", {'facing': StringTag("up")}),
    ((2, 0, 0), "universal_minecraft:dirt", {}),
    ((2, 0, 1), "universal_minecraft:dirt", {}),
    ((2, 0, 2), "universal_minecraft:dirt", {}),
    ((2, 0, 3), "universal_minecraft:dirt", {}),
    ((2, 0, 4), "universal_minecraft:dirt", {}),
    ((2, 0, 5), "universal_minecraft:dirt", {}),
    ((2, 0, 6), "universal_minecraft:dirt", {}),
    ((2, 0, 7), "universal_minecraft:dirt", {}),
    ((2, 0, 8), "universal_minecraft:dirt", {}),
    ((2, 0, 9), "universal_minecraft:dirt", {}),
    ((2, 0, 10), "universal_minecraft:dirt", {}),
    ((2, 0, 11), "universal_minecraft:dirt", {}),
    ((2, 0, 12), "universal_minecraft:dirt", {}),
    ((2, 1, 0), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((2, 1, 1), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((2, 1, 2), "universal_minecraft:dirt", {}),
    ((2, 1, 3), "universal_minecraft:dirt", {}),
    ((2, 1, 4), "universal_minecraft:dirt", {}),
    ((2, 1, 5), "universal_minecraft:dirt", {}),
    ((2, 1, 6), "universal_minecraft:dirt", {}),
    ((2, 1, 7), "universal_minecraft:dirt", {}),
    ((2, 1, 8), "universal_minecraft:dirt", {}),
    ((2, 1, 9), "universal_minecraft:dirt", {}),
    ((2, 1, 10), "universal_minecraft:dirt", {}),
    ((2, 1, 11), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((2, 1, 12), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((2, 2, 2), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((2, 2, 3), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((2, 2, 4), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((2, 2, 5), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((2, 2, 6), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((2, 2, 7), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((2, 2, 8), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((2, 2, 9), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((2, 2, 10), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((2, 3, 2), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((2, 3, 3), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((2, 3, 4), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((2, 3, 5), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((2, 3, 6), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((2, 3, 7), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((2, 3, 8), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((2, 3, 9), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((2, 3, 10), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((2, 4, 2), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((2, 4, 3), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((2, 4, 4), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((2, 4, 5), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((2, 4, 6), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((2, 4, 7), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((2, 4, 8), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((2, 4, 9), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((2, 4, 10), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((2, 5, 1), "universal_minecraft:bars", {'material': StringTag("iron"), 'east': StringTag("false"), 'north': StringTag("false"), 'south': StringTag("true"), 'west': StringTag("true")}),
    ((2, 5, 2), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((2, 5, 3), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((2, 5, 4), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((2, 5, 5), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((2, 5, 6), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((2, 5, 7), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((2, 5, 8), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((2, 5, 9), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((2, 5, 10), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((2, 5, 11), "universal_minecraft:bars", {'material': StringTag("iron"), 'east': StringTag("false"), 'north': StringTag("true"), 'south': StringTag("false"), 'west': StringTag("true")}),
    ((2, 6, 1), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((2, 6, 2), "universal_minecraft:slab", {'material': StringTag("stone_brick"), 'type': StringTag("bottom")}),
    ((2, 6, 3), "universal_minecraft:slab", {'material': StringTag("stone_brick"), 'type': StringTag("bottom")}),
    ((2, 6, 4), "universal_minecraft:slab", {'material': StringTag("stone_brick"), 'type': StringTag("bottom")}),
    ((2, 6, 5), "universal_minecraft:slab", {'material': StringTag("stone_brick"), 'type': StringTag("bottom")}),
    ((2, 6, 6), "universal_minecraft:slab", {'material': StringTag("stone_brick"), 'type': StringTag("bottom")}),
    ((2, 6, 7), "universal_minecraft:slab", {'material': StringTag("stone_brick"), 'type': StringTag("bottom")}),
    ((2, 6, 8), "universal_minecraft:slab", {'material': StringTag("stone_brick"), 'type': StringTag("bottom")}),
    ((2, 6, 9), "universal_minecraft:slab", {'material': StringTag("stone_brick"), 'type': StringTag("bottom")}),
    ((2, 6, 10), "universal_minecraft:slab", {'material': StringTag("stone_brick"), 'type': StringTag("bottom")}),
    ((2, 6, 11), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((2, 7, 1), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((2, 7, 11), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((3, 0, 0), "universal_minecraft:dirt", {}),
    ((3, 0, 1), "universal_minecraft:dirt", {}),
    ((3, 0, 2), "universal_minecraft:dirt", {}),
    ((3, 0, 3), "universal_minecraft:dirt", {}),
    ((3, 0, 4), "universal_minecraft:dirt", {}),
    ((3, 0, 5), "universal_minecraft:dirt", {}),
    ((3, 0, 6), "universal_minecraft:dirt", {}),
    ((3, 0, 7), "universal_minecraft:dirt", {}),
    ((3, 0, 8), "universal_minecraft:dirt", {}),
    ((3, 0, 9), "universal_minecraft:dirt", {}),
    ((3, 0, 10), "universal_minecraft:dirt", {}),
    ((3, 0, 11), "universal_minecraft:dirt", {}),
    ((3, 0, 12), "universal_minecraft:dirt", {}),
    ((3, 1, 0), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((3, 1, 1), "universal_minecraft:dirt", {}),
    ((3, 1, 2), "universal_minecraft:dirt", {}),
    ((3, 1, 3), "universal_minecraft:dirt", {}),
    ((3, 1, 4), "universal_minecraft:dirt", {}),
    ((3, 1, 5), "universal_minecraft:dirt", {}),
    ((3, 1, 6), "universal_minecraft:dirt", {}),
    ((3, 1, 7), "universal_minecraft:dirt", {}),
    ((3, 1, 8), "universal_minecraft:dirt", {}),
    ((3, 1, 9), "universal_minecraft:dirt", {}),
    ((3, 1, 10), "universal_minecraft:dirt", {}),
    ((3, 1, 11), "universal_minecraft:dirt", {}),
    ((3, 1, 12), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((3, 2, 1), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((3, 2, 2), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((3, 2, 3), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("bottom")}),
    ((3, 2, 4), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("bottom")}),
    ((3, 2, 5), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("bottom")}),
    ((3, 2, 6), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("bottom")}),
    ((3, 2, 7), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("bottom")}),
    ((3, 2, 8), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("bottom")}),
    ((3, 2, 9), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("bottom")}),
    ((3, 2, 10), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((3, 2, 11), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((3, 3, 2), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((3, 3, 10), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((3, 4, 2), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((3, 4, 10), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((3, 5, 1), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("south"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((3, 5, 2), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((3, 5, 3), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((3, 5, 4), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((3, 5, 5), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((3, 5, 6), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("double")}),
    ((3, 5, 7), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((3, 5, 8), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((3, 5, 9), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((3, 5, 10), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((3, 5, 11), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("north"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((3, 6, 1), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((3, 6, 2), "universal_minecraft:slab", {'material': StringTag("stone_brick"), 'type': StringTag("bottom")}),
    ((3, 6, 10), "universal_minecraft:slab", {'material': StringTag("stone_brick"), 'type': StringTag("bottom")}),
    ((3, 6, 11), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((3, 7, 1), "universal_minecraft:bars", {'material': StringTag("iron"), 'east': StringTag("false"), 'north': StringTag("false"), 'south': StringTag("false"), 'west': StringTag("true")}),
    ((3, 7, 11), "universal_minecraft:bars", {'material': StringTag("iron"), 'east': StringTag("false"), 'north': StringTag("false"), 'south': StringTag("false"), 'west': StringTag("true")}),
    ((4, 0, 0), "universal_minecraft:dirt", {}),
    ((4, 0, 1), "universal_minecraft:dirt", {}),
    ((4, 0, 2), "universal_minecraft:dirt", {}),
    ((4, 0, 3), "universal_minecraft:dirt", {}),
    ((4, 0, 4), "universal_minecraft:dirt", {}),
    ((4, 0, 5), "universal_minecraft:dirt", {}),
    ((4, 0, 6), "universal_minecraft:dirt", {}),
    ((4, 0, 7), "universal_minecraft:dirt", {}),
    ((4, 0, 8), "universal_minecraft:dirt", {}),
    ((4, 0, 9), "universal_minecraft:dirt", {}),
    ((4, 0, 10), "universal_minecraft:dirt", {}),
    ((4, 0, 11), "universal_minecraft:dirt", {}),
    ((4, 0, 12), "universal_minecraft:dirt", {}),
    ((4, 1, 0), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((4, 1, 1), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((4, 1, 2), "universal_minecraft:dirt", {}),
    ((4, 1, 3), "universal_minecraft:dirt", {}),
    ((4, 1, 4), "universal_minecraft:dirt", {}),
    ((4, 1, 5), "universal_minecraft:dirt", {}),
    ((4, 1, 6), "universal_minecraft:dirt", {}),
    ((4, 1, 7), "universal_minecraft:dirt", {}),
    ((4, 1, 8), "universal_minecraft:dirt", {}),
    ((4, 1, 9), "universal_minecraft:dirt", {}),
    ((4, 1, 10), "universal_minecraft:dirt", {}),
    ((4, 1, 11), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((4, 1, 12), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((4, 2, 2), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((4, 2, 3), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("bottom")}),
    ((4, 2, 4), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("bottom")}),
    ((4, 2, 5), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("bottom")}),
    ((4, 2, 6), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("bottom")}),
    ((4, 2, 7), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("bottom")}),
    ((4, 2, 8), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("bottom")}),
    ((4, 2, 9), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("bottom")}),
    ((4, 2, 10), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((4, 3, 2), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((4, 3, 10), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("west"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((4, 4, 2), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((4, 4, 10), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("west"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((4, 5, 2), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((4, 5, 3), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((4, 5, 4), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((4, 5, 5), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((4, 5, 6), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("double")}),
    ((4, 5, 7), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((4, 5, 8), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((4, 5, 9), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((4, 5, 10), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((4, 6, 1), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((4, 6, 2), "universal_minecraft:slab", {'material': StringTag("stone_brick"), 'type': StringTag("bottom")}),
    ((4, 6, 10), "universal_minecraft:slab", {'material': StringTag("stone_brick"), 'type': StringTag("bottom")}),
    ((4, 6, 11), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((5, 0, 0), "universal_minecraft:dirt", {}),
    ((5, 0, 1), "universal_minecraft:dirt", {}),
    ((5, 0, 2), "universal_minecraft:dirt", {}),
    ((5, 0, 3), "universal_minecraft:dirt", {}),
    ((5, 0, 4), "universal_minecraft:dirt", {}),
    ((5, 0, 5), "universal_minecraft:dirt", {}),
    ((5, 0, 6), "universal_minecraft:dirt", {}),
    ((5, 0, 7), "universal_minecraft:dirt", {}),
    ((5, 0, 8), "universal_minecraft:dirt", {}),
    ((5, 0, 9), "universal_minecraft:dirt", {}),
    ((5, 0, 10), "universal_minecraft:dirt", {}),
    ((5, 0, 11), "universal_minecraft:dirt", {}),
    ((5, 0, 12), "universal_minecraft:dirt", {}),
    ((5, 1, 0), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((5, 1, 1), "universal_minecraft:dirt", {}),
    ((5, 1, 2), "universal_minecraft:dirt", {}),
    ((5, 1, 3), "universal_minecraft:dirt", {}),
    ((5, 1, 4), "universal_minecraft:dirt", {}),
    ((5, 1, 5), "universal_minecraft:dirt", {}),
    ((5, 1, 6), "universal_minecraft:dirt", {}),
    ((5, 1, 7), "universal_minecraft:dirt", {}),
    ((5, 1, 8), "universal_minecraft:dirt", {}),
    ((5, 1, 9), "universal_minecraft:dirt", {}),
    ((5, 1, 10), "universal_minecraft:dirt", {}),
    ((5, 1, 11), "universal_minecraft:dirt", {}),
    ((5, 1, 12), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((5, 2, 1), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((5, 2, 2), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((5, 2, 3), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("bottom")}),
    ((5, 2, 4), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("bottom")}),
    ((5, 2, 5), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("bottom")}),
    ((5, 2, 6), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("bottom")}),
    ((5, 2, 7), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("bottom")}),
    ((5, 2, 8), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("bottom")}),
    ((5, 2, 9), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("bottom")}),
    ((5, 2, 10), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((5, 2, 11), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("east"), 'half': StringTag("bottom"), 'shape': StringTag("outer_left")}),
    ((5, 3, 2), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((5, 3, 10), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((5, 4, 2), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((5, 4, 9), "universal_minecraft:torch", {'facing': StringTag("north")}),
    ((5, 4, 10), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((5, 4, 11), "universal_minecraft:torch", {'facing': StringTag("south")}),
    ((5, 5, 1), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("south"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((5, 5, 2), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((5, 5, 3), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((5, 5, 4), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((5, 5, 5), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((5, 5, 6), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("double")}),
    ((5, 5, 7), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((5, 5, 8), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((5, 5, 9), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((5, 5, 10), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((5, 5, 11), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("north"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((5, 6, 1), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((5, 6, 2), "universal_minecraft:slab", {'material': StringTag("stone_brick"), 'type': StringTag("bottom")}),
    ((5, 6, 10), "universal_minecraft:slab", {'material': StringTag("stone_brick"), 'type': StringTag("bottom")}),
    ((5, 6, 11), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((5, 7, 1), "universal_minecraft:bars", {'material': StringTag("iron"), 'east': StringTag("true"), 'north': StringTag("false"), 'south': StringTag("false"), 'west': StringTag("false")}),
    ((5, 7, 11), "universal_minecraft:bars", {'material': StringTag("iron"), 'east': StringTag("true"), 'north': StringTag("false"), 'south': StringTag("false"), 'west': StringTag("false")}),
    ((6, 0, 0), "universal_minecraft:dirt", {}),
    ((6, 0, 1), "universal_minecraft:dirt", {}),
    ((6, 0, 2), "universal_minecraft:dirt", {}),
    ((6, 0, 3), "universal_minecraft:dirt", {}),
    ((6, 0, 4), "universal_minecraft:dirt", {}),
    ((6, 0, 5), "universal_minecraft:dirt", {}),
    ((6, 0, 6), "universal_minecraft:dirt", {}),
    ((6, 0, 7), "universal_minecraft:dirt", {}),
    ((6, 0, 8), "universal_minecraft:dirt", {}),
    ((6, 0, 9), "universal_minecraft:dirt", {}),
    ((6, 0, 10), "universal_minecraft:dirt", {}),
    ((6, 0, 11), "universal_minecraft:dirt", {}),
    ((6, 0, 12), "universal_minecraft:dirt", {}),
    ((6, 1, 0), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((6, 1, 1), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((6, 1, 2), "universal_minecraft:dirt", {}),
    ((6, 1, 3), "universal_minecraft:dirt", {}),
    ((6, 1, 4), "universal_minecraft:dirt", {}),
    ((6, 1, 5), "universal_minecraft:dirt", {}),
    ((6, 1, 6), "universal_minecraft:dirt", {}),
    ((6, 1, 7), "universal_minecraft:dirt", {}),
    ((6, 1, 8), "universal_minecraft:dirt", {}),
    ((6, 1, 9), "universal_minecraft:dirt", {}),
    ((6, 1, 10), "universal_minecraft:dirt", {}),
    ((6, 1, 11), "universal_minecraft:dirt", {}),
    ((6, 1, 12), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((6, 2, 2), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((6, 2, 3), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("bottom")}),
    ((6, 2, 4), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("bottom")}),
    ((6, 2, 5), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("bottom")}),
    ((6, 2, 6), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("bottom")}),
    ((6, 2, 7), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("bottom")}),
    ((6, 2, 8), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("bottom")}),
    ((6, 2, 9), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("bottom")}),
    ((6, 2, 10), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((6, 2, 11), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((6, 3, 2), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((6, 4, 2), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((6, 5, 2), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((6, 5, 3), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("double")}),
    ((6, 5, 4), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("double")}),
    ((6, 5, 5), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("double")}),
    ((6, 5, 6), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("double")}),
    ((6, 5, 7), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("double")}),
    ((6, 5, 8), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("double")}),
    ((6, 5, 9), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("double")}),
    ((6, 5, 10), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((6, 6, 1), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((6, 6, 2), "universal_minecraft:slab", {'material': StringTag("stone_brick"), 'type': StringTag("bottom")}),
    ((6, 6, 10), "universal_minecraft:slab", {'material': StringTag("stone_brick"), 'type': StringTag("bottom")}),
    ((6, 6, 11), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((6, 7, 1), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((6, 7, 11), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((7, 0, 0), "universal_minecraft:dirt", {}),
    ((7, 0, 1), "universal_minecraft:dirt", {}),
    ((7, 0, 2), "universal_minecraft:dirt", {}),
    ((7, 0, 3), "universal_minecraft:dirt", {}),
    ((7, 0, 4), "universal_minecraft:dirt", {}),
    ((7, 0, 5), "universal_minecraft:dirt", {}),
    ((7, 0, 6), "universal_minecraft:dirt", {}),
    ((7, 0, 7), "universal_minecraft:dirt", {}),
    ((7, 0, 8), "universal_minecraft:dirt", {}),
    ((7, 0, 9), "universal_minecraft:dirt", {}),
    ((7, 0, 10), "universal_minecraft:dirt", {}),
    ((7, 0, 11), "universal_minecraft:dirt", {}),
    ((7, 0, 12), "universal_minecraft:dirt", {}),
    ((7, 1, 0), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((7, 1, 1), "universal_minecraft:dirt", {}),
    ((7, 1, 2), "universal_minecraft:dirt", {}),
    ((7, 1, 3), "universal_minecraft:dirt", {}),
    ((7, 1, 4), "universal_minecraft:dirt", {}),
    ((7, 1, 5), "universal_minecraft:dirt", {}),
    ((7, 1, 6), "universal_minecraft:dirt", {}),
    ((7, 1, 7), "universal_minecraft:dirt", {}),
    ((7, 1, 8), "universal_minecraft:dirt", {}),
    ((7, 1, 9), "universal_minecraft:dirt", {}),
    ((7, 1, 10), "universal_minecraft:dirt", {}),
    ((7, 1, 11), "universal_minecraft:dirt", {}),
    ((7, 1, 12), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((7, 2, 1), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((7, 2, 2), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((7, 2, 3), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("bottom")}),
    ((7, 2, 4), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("bottom")}),
    ((7, 2, 5), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("bottom")}),
    ((7, 2, 6), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("bottom")}),
    ((7, 2, 7), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("bottom")}),
    ((7, 2, 8), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("bottom")}),
    ((7, 2, 9), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("bottom")}),
    ((7, 2, 10), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((7, 2, 11), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("west"), 'half': StringTag("bottom"), 'shape': StringTag("outer_right")}),
    ((7, 3, 2), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((7, 3, 10), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((7, 4, 2), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((7, 4, 9), "universal_minecraft:torch", {'facing': StringTag("north")}),
    ((7, 4, 10), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((7, 4, 11), "universal_minecraft:torch", {'facing': StringTag("south")}),
    ((7, 5, 1), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("south"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((7, 5, 2), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((7, 5, 3), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((7, 5, 4), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((7, 5, 5), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((7, 5, 6), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("double")}),
    ((7, 5, 7), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((7, 5, 8), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((7, 5, 9), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((7, 5, 10), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((7, 5, 11), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("north"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((7, 6, 1), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((7, 6, 2), "universal_minecraft:slab", {'material': StringTag("stone_brick"), 'type': StringTag("bottom")}),
    ((7, 6, 10), "universal_minecraft:slab", {'material': StringTag("stone_brick"), 'type': StringTag("bottom")}),
    ((7, 6, 11), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((7, 7, 1), "universal_minecraft:bars", {'material': StringTag("iron"), 'east': StringTag("false"), 'north': StringTag("false"), 'south': StringTag("false"), 'west': StringTag("true")}),
    ((7, 7, 11), "universal_minecraft:bars", {'material': StringTag("iron"), 'east': StringTag("false"), 'north': StringTag("false"), 'south': StringTag("false"), 'west': StringTag("true")}),
    ((8, 0, 0), "universal_minecraft:dirt", {}),
    ((8, 0, 1), "universal_minecraft:dirt", {}),
    ((8, 0, 2), "universal_minecraft:dirt", {}),
    ((8, 0, 3), "universal_minecraft:dirt", {}),
    ((8, 0, 4), "universal_minecraft:dirt", {}),
    ((8, 0, 5), "universal_minecraft:dirt", {}),
    ((8, 0, 6), "universal_minecraft:dirt", {}),
    ((8, 0, 7), "universal_minecraft:dirt", {}),
    ((8, 0, 8), "universal_minecraft:dirt", {}),
    ((8, 0, 9), "universal_minecraft:dirt", {}),
    ((8, 0, 10), "universal_minecraft:dirt", {}),
    ((8, 0, 11), "universal_minecraft:dirt", {}),
    ((8, 0, 12), "universal_minecraft:dirt", {}),
    ((8, 1, 0), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((8, 1, 1), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((8, 1, 2), "universal_minecraft:dirt", {}),
    ((8, 1, 3), "universal_minecraft:dirt", {}),
    ((8, 1, 4), "universal_minecraft:dirt", {}),
    ((8, 1, 5), "universal_minecraft:dirt", {}),
    ((8, 1, 6), "universal_minecraft:dirt", {}),
    ((8, 1, 7), "universal_minecraft:dirt", {}),
    ((8, 1, 8), "universal_minecraft:dirt", {}),
    ((8, 1, 9), "universal_minecraft:dirt", {}),
    ((8, 1, 10), "universal_minecraft:dirt", {}),
    ((8, 1, 11), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((8, 1, 12), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((8, 2, 2), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((8, 2, 3), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("bottom")}),
    ((8, 2, 4), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("bottom")}),
    ((8, 2, 5), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("bottom")}),
    ((8, 2, 6), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("bottom")}),
    ((8, 2, 7), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("bottom")}),
    ((8, 2, 8), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("bottom")}),
    ((8, 2, 9), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("bottom")}),
    ((8, 2, 10), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((8, 3, 2), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((8, 3, 10), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("east"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((8, 4, 2), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((8, 4, 10), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("east"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((8, 5, 2), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((8, 5, 3), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((8, 5, 4), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((8, 5, 5), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((8, 5, 6), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("double")}),
    ((8, 5, 7), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((8, 5, 8), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((8, 5, 9), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((8, 5, 10), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((8, 6, 1), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((8, 6, 2), "universal_minecraft:slab", {'material': StringTag("stone_brick"), 'type': StringTag("bottom")}),
    ((8, 6, 10), "universal_minecraft:slab", {'material': StringTag("stone_brick"), 'type': StringTag("bottom")}),
    ((8, 6, 11), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((9, 0, 0), "universal_minecraft:dirt", {}),
    ((9, 0, 1), "universal_minecraft:dirt", {}),
    ((9, 0, 2), "universal_minecraft:dirt", {}),
    ((9, 0, 3), "universal_minecraft:dirt", {}),
    ((9, 0, 4), "universal_minecraft:dirt", {}),
    ((9, 0, 5), "universal_minecraft:dirt", {}),
    ((9, 0, 6), "universal_minecraft:dirt", {}),
    ((9, 0, 7), "universal_minecraft:dirt", {}),
    ((9, 0, 8), "universal_minecraft:dirt", {}),
    ((9, 0, 9), "universal_minecraft:dirt", {}),
    ((9, 0, 10), "universal_minecraft:dirt", {}),
    ((9, 0, 11), "universal_minecraft:dirt", {}),
    ((9, 0, 12), "universal_minecraft:dirt", {}),
    ((9, 1, 0), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((9, 1, 1), "universal_minecraft:dirt", {}),
    ((9, 1, 2), "universal_minecraft:dirt", {}),
    ((9, 1, 3), "universal_minecraft:dirt", {}),
    ((9, 1, 4), "universal_minecraft:dirt", {}),
    ((9, 1, 5), "universal_minecraft:dirt", {}),
    ((9, 1, 6), "universal_minecraft:dirt", {}),
    ((9, 1, 7), "universal_minecraft:dirt", {}),
    ((9, 1, 8), "universal_minecraft:dirt", {}),
    ((9, 1, 9), "universal_minecraft:dirt", {}),
    ((9, 1, 10), "universal_minecraft:dirt", {}),
    ((9, 1, 11), "universal_minecraft:dirt", {}),
    ((9, 1, 12), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((9, 2, 1), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((9, 2, 2), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((9, 2, 3), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("bottom")}),
    ((9, 2, 4), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("bottom")}),
    ((9, 2, 5), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("bottom")}),
    ((9, 2, 6), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("bottom")}),
    ((9, 2, 7), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("bottom")}),
    ((9, 2, 8), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("bottom")}),
    ((9, 2, 9), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("bottom")}),
    ((9, 2, 10), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((9, 2, 11), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((9, 3, 2), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((9, 3, 3), "universal_minecraft:ladder", {'facing': StringTag("south")}),
    ((9, 3, 10), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((9, 4, 2), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((9, 4, 3), "universal_minecraft:ladder", {'facing': StringTag("south")}),
    ((9, 4, 10), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((9, 5, 1), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("south"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((9, 5, 2), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((9, 5, 3), "universal_minecraft:ladder", {'facing': StringTag("south")}),
    ((9, 5, 4), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((9, 5, 5), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((9, 5, 6), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("double")}),
    ((9, 5, 7), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((9, 5, 8), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((9, 5, 9), "universal_minecraft:slab", {'material': StringTag("dark_oak"), 'type': StringTag("top")}),
    ((9, 5, 10), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((9, 5, 11), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("north"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((9, 6, 1), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((9, 6, 2), "universal_minecraft:slab", {'material': StringTag("stone_brick"), 'type': StringTag("bottom")}),
    ((9, 6, 10), "universal_minecraft:slab", {'material': StringTag("stone_brick"), 'type': StringTag("bottom")}),
    ((9, 6, 11), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((9, 7, 1), "universal_minecraft:bars", {'material': StringTag("iron"), 'east': StringTag("true"), 'north': StringTag("false"), 'south': StringTag("false"), 'west': StringTag("false")}),
    ((9, 7, 11), "universal_minecraft:bars", {'material': StringTag("iron"), 'east': StringTag("true"), 'north': StringTag("false"), 'south': StringTag("false"), 'west': StringTag("false")}),
    ((10, 0, 0), "universal_minecraft:dirt", {}),
    ((10, 0, 1), "universal_minecraft:dirt", {}),
    ((10, 0, 2), "universal_minecraft:dirt", {}),
    ((10, 0, 3), "universal_minecraft:dirt", {}),
    ((10, 0, 4), "universal_minecraft:dirt", {}),
    ((10, 0, 5), "universal_minecraft:dirt", {}),
    ((10, 0, 6), "universal_minecraft:dirt", {}),
    ((10, 0, 7), "universal_minecraft:dirt", {}),
    ((10, 0, 8), "universal_minecraft:dirt", {}),
    ((10, 0, 9), "universal_minecraft:dirt", {}),
    ((10, 0, 10), "universal_minecraft:dirt", {}),
    ((10, 0, 11), "universal_minecraft:dirt", {}),
    ((10, 0, 12), "universal_minecraft:dirt", {}),
    ((10, 1, 0), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((10, 1, 1), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((10, 1, 2), "universal_minecraft:dirt", {}),
    ((10, 1, 3), "universal_minecraft:dirt", {}),
    ((10, 1, 4), "universal_minecraft:dirt", {}),
    ((10, 1, 5), "universal_minecraft:dirt", {}),
    ((10, 1, 6), "universal_minecraft:dirt", {}),
    ((10, 1, 7), "universal_minecraft:dirt", {}),
    ((10, 1, 8), "universal_minecraft:dirt", {}),
    ((10, 1, 9), "universal_minecraft:dirt", {}),
    ((10, 1, 10), "universal_minecraft:dirt", {}),
    ((10, 1, 11), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((10, 1, 12), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((10, 2, 2), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((10, 2, 3), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((10, 2, 4), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((10, 2, 5), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((10, 2, 6), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((10, 2, 7), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((10, 2, 8), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((10, 2, 9), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((10, 2, 10), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((10, 3, 2), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((10, 3, 3), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((10, 3, 4), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((10, 3, 5), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((10, 3, 6), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((10, 3, 7), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((10, 3, 8), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((10, 3, 9), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((10, 3, 10), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((10, 4, 2), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((10, 4, 3), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((10, 4, 4), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((10, 4, 5), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((10, 4, 6), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((10, 4, 7), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((10, 4, 8), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((10, 4, 9), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((10, 4, 10), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((10, 5, 1), "universal_minecraft:bars", {'material': StringTag("iron"), 'east': StringTag("true"), 'north': StringTag("false"), 'south': StringTag("true"), 'west': StringTag("false")}),
    ((10, 5, 2), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((10, 5, 3), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((10, 5, 4), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((10, 5, 5), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((10, 5, 6), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((10, 5, 7), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((10, 5, 8), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((10, 5, 9), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((10, 5, 10), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((10, 5, 11), "universal_minecraft:bars", {'material': StringTag("iron"), 'east': StringTag("true"), 'north': StringTag("true"), 'south': StringTag("false"), 'west': StringTag("false")}),
    ((10, 6, 1), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((10, 6, 2), "universal_minecraft:slab", {'material': StringTag("stone_brick"), 'type': StringTag("bottom")}),
    ((10, 6, 3), "universal_minecraft:slab", {'material': StringTag("stone_brick"), 'type': StringTag("bottom")}),
    ((10, 6, 4), "universal_minecraft:slab", {'material': StringTag("stone_brick"), 'type': StringTag("bottom")}),
    ((10, 6, 5), "universal_minecraft:slab", {'material': StringTag("stone_brick"), 'type': StringTag("bottom")}),
    ((10, 6, 6), "universal_minecraft:slab", {'material': StringTag("stone_brick"), 'type': StringTag("bottom")}),
    ((10, 6, 7), "universal_minecraft:slab", {'material': StringTag("stone_brick"), 'type': StringTag("bottom")}),
    ((10, 6, 8), "universal_minecraft:slab", {'material': StringTag("stone_brick"), 'type': StringTag("bottom")}),
    ((10, 6, 9), "universal_minecraft:slab", {'material': StringTag("stone_brick"), 'type': StringTag("bottom")}),
    ((10, 6, 10), "universal_minecraft:slab", {'material': StringTag("stone_brick"), 'type': StringTag("bottom")}),
    ((10, 6, 11), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((10, 7, 1), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((10, 7, 11), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((11, 0, 0), "universal_minecraft:dirt", {}),
    ((11, 0, 1), "universal_minecraft:dirt", {}),
    ((11, 0, 2), "universal_minecraft:dirt", {}),
    ((11, 0, 3), "universal_minecraft:dirt", {}),
    ((11, 0, 4), "universal_minecraft:dirt", {}),
    ((11, 0, 5), "universal_minecraft:dirt", {}),
    ((11, 0, 6), "universal_minecraft:dirt", {}),
    ((11, 0, 7), "universal_minecraft:dirt", {}),
    ((11, 0, 8), "universal_minecraft:dirt", {}),
    ((11, 0, 9), "universal_minecraft:dirt", {}),
    ((11, 0, 10), "universal_minecraft:dirt", {}),
    ((11, 0, 11), "universal_minecraft:dirt", {}),
    ((11, 0, 12), "universal_minecraft:dirt", {}),
    ((11, 1, 0), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((11, 1, 1), "universal_minecraft:dirt", {}),
    ((11, 1, 2), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((11, 1, 3), "universal_minecraft:dirt", {}),
    ((11, 1, 4), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((11, 1, 5), "universal_minecraft:dirt", {}),
    ((11, 1, 6), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((11, 1, 7), "universal_minecraft:dirt", {}),
    ((11, 1, 8), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((11, 1, 9), "universal_minecraft:dirt", {}),
    ((11, 1, 10), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((11, 1, 11), "universal_minecraft:dirt", {}),
    ((11, 1, 12), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((11, 2, 1), "universal_minecraft:stone_bricks", {'variant': StringTag("chiseled")}),
    ((11, 2, 3), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("west"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((11, 2, 5), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("west"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((11, 2, 7), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("west"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((11, 2, 9), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("west"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((11, 2, 11), "universal_minecraft:stone_bricks", {'variant': StringTag("chiseled")}),
    ((11, 3, 1), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((11, 3, 11), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((11, 4, 1), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((11, 4, 11), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((11, 5, 1), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((11, 5, 2), "universal_minecraft:bars", {'material': StringTag("iron"), 'east': StringTag("false"), 'north': StringTag("true"), 'south': StringTag("false"), 'west': StringTag("true")}),
    ((11, 5, 3), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("west"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((11, 5, 5), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("west"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((11, 5, 7), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("west"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((11, 5, 9), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("west"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((11, 5, 10), "universal_minecraft:bars", {'material': StringTag("iron"), 'east': StringTag("false"), 'north': StringTag("false"), 'south': StringTag("true"), 'west': StringTag("true")}),
    ((11, 5, 11), "universal_minecraft:log", {'material': StringTag("spruce"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((11, 6, 1), "universal_minecraft:stone_bricks", {'variant': StringTag("chiseled")}),
    ((11, 6, 2), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((11, 6, 3), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((11, 6, 4), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((11, 6, 5), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((11, 6, 6), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((11, 6, 7), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((11, 6, 8), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((11, 6, 9), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((11, 6, 10), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((11, 6, 11), "universal_minecraft:stone_bricks", {'variant': StringTag("chiseled")}),
    ((11, 7, 1), "universal_minecraft:wall", {'material': StringTag("cobblestone"), 'east': StringTag("none"), 'north': StringTag("none"), 'south': StringTag("low"), 'up': StringTag("true"), 'west': StringTag("low")}),
    ((11, 7, 2), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((11, 7, 3), "universal_minecraft:bars", {'material': StringTag("iron"), 'east': StringTag("false"), 'north': StringTag("true"), 'south': StringTag("false"), 'west': StringTag("false")}),
    ((11, 7, 5), "universal_minecraft:bars", {'material': StringTag("iron"), 'east': StringTag("false"), 'north': StringTag("false"), 'south': StringTag("true"), 'west': StringTag("false")}),
    ((11, 7, 6), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((11, 7, 7), "universal_minecraft:bars", {'material': StringTag("iron"), 'east': StringTag("false"), 'north': StringTag("true"), 'south': StringTag("false"), 'west': StringTag("false")}),
    ((11, 7, 9), "universal_minecraft:bars", {'material': StringTag("iron"), 'east': StringTag("false"), 'north': StringTag("false"), 'south': StringTag("true"), 'west': StringTag("false")}),
    ((11, 7, 10), "universal_minecraft:bars", {'material': StringTag("iron"), 'east': StringTag("false"), 'north': StringTag("true"), 'south': StringTag("true"), 'west': StringTag("false")}),
    ((11, 7, 11), "universal_minecraft:wall", {'material': StringTag("cobblestone"), 'east': StringTag("none"), 'north': StringTag("low"), 'south': StringTag("none"), 'up': StringTag("true"), 'west': StringTag("low")}),
    ((11, 8, 1), "universal_minecraft:wall", {'material': StringTag("cobblestone"), 'east': StringTag("none"), 'north': StringTag("none"), 'south': StringTag("none"), 'up': StringTag("true"), 'west': StringTag("none")}),
    ((11, 8, 11), "universal_minecraft:wall", {'material': StringTag("cobblestone"), 'east': StringTag("none"), 'north': StringTag("none"), 'south': StringTag("none"), 'up': StringTag("true"), 'west': StringTag("none")}),
    ((11, 9, 1), "universal_minecraft:torch", {'facing': StringTag("up")}),
    ((11, 9, 11), "universal_minecraft:torch", {'facing': StringTag("up")}),
    ((12, 0, 0), "universal_minecraft:dirt", {}),
    ((12, 0, 1), "universal_minecraft:dirt", {}),
    ((12, 0, 2), "universal_minecraft:dirt", {}),
    ((12, 0, 3), "universal_minecraft:dirt", {}),
    ((12, 0, 4), "universal_minecraft:dirt", {}),
    ((12, 0, 5), "universal_minecraft:dirt", {}),
    ((12, 0, 6), "universal_minecraft:dirt", {}),
    ((12, 0, 7), "universal_minecraft:dirt", {}),
    ((12, 0, 8), "universal_minecraft:dirt", {}),
    ((12, 0, 9), "universal_minecraft:dirt", {}),
    ((12, 0, 10), "universal_minecraft:dirt", {}),
    ((12, 0, 11), "universal_minecraft:dirt", {}),
    ((12, 0, 12), "universal_minecraft:dirt", {}),
    ((12, 1, 0), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((12, 1, 1), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((12, 1, 2), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((12, 1, 3), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((12, 1, 4), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((12, 1, 5), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((12, 1, 6), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((12, 1, 7), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((12, 1, 8), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((12, 1, 9), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((12, 1, 10), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((12, 1, 11), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((12, 1, 12), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
]
