# Auto-generated building blueprint
NAME = "bp_021"
BLOCKS = [
    ((0, 0, 0), "universal_minecraft:dirt", {}),
    ((0, 0, 1), "universal_minecraft:dirt", {}),
    ((0, 0, 2), "universal_minecraft:dirt", {}),
    ((0, 0, 3), "universal_minecraft:dirt", {}),
    ((0, 0, 4), "universal_minecraft:dirt", {}),
    ((0, 0, 5), "universal_minecraft:dirt", {}),
    ((0, 0, 6), "universal_minecraft:dirt", {}),
    ((0, 0, 7), "universal_minecraft:dirt", {}),
    ((0, 0, 8), "universal_minecraft:dirt", {}),
    ((0, 0, 9), "universal_minecraft:dirt", {}),
    ((0, 0, 10), "universal_minecraft:dirt", {}),
    ((0, 1, 0), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((0, 1, 1), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((0, 1, 2), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((0, 1, 3), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((0, 1, 4), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((0, 1, 5), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((0, 1, 6), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((0, 1, 7), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((0, 1, 8), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((0, 1, 9), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((0, 1, 10), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((1, 0, 0), "universal_minecraft:dirt", {}),
    ((1, 0, 1), "universal_minecraft:dirt", {}),
    ((1, 0, 2), "universal_minecraft:dirt", {}),
    ((1, 0, 3), "universal_minecraft:dirt", {}),
    ((1, 0, 4), "universal_minecraft:dirt", {}),
    ((1, 0, 5), "universal_minecraft:dirt", {}),
    ((1, 0, 6), "universal_minecraft:dirt", {}),
    ((1, 0, 7), "universal_minecraft:dirt", {}),
    ((1, 0, 8), "universal_minecraft:dirt", {}),
    ((1, 0, 9), "universal_minecraft:dirt", {}),
    ((1, 0, 10), "universal_minecraft:dirt", {}),
    ((1, 1, 0), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((1, 1, 1), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((1, 1, 2), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((1, 1, 3), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((1, 1, 4), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((1, 1, 5), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((1, 1, 6), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((1, 1, 7), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((1, 1, 8), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((1, 1, 9), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((1, 1, 10), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((1, 2, 5), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("east"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((2, 0, 0), "universal_minecraft:dirt", {}),
    ((2, 0, 1), "universal_minecraft:dirt", {}),
    ((2, 0, 2), "universal_minecraft:dirt", {}),
    ((2, 0, 3), "universal_minecraft:dirt", {}),
    ((2, 0, 4), "universal_minecraft:dirt", {}),
    ((2, 0, 5), "universal_minecraft:dirt", {}),
    ((2, 0, 6), "universal_minecraft:dirt", {}),
    ((2, 0, 7), "universal_minecraft:dirt", {}),
    ((2, 0, 8), "universal_minecraft:dirt", {}),
    ((2, 0, 9), "universal_minecraft:dirt", {}),
    ((2, 0, 10), "universal_minecraft:dirt", {}),
    ((2, 1, 0), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((2, 1, 1), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((2, 1, 2), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((2, 1, 3), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((2, 1, 4), "universal_minecraft:dirt", {}),
    ((2, 1, 5), "universal_minecraft:dirt", {}),
    ((2, 1, 6), "universal_minecraft:dirt", {}),
    ((2, 1, 7), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((2, 1, 8), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((2, 1, 9), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((2, 1, 10), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((2, 2, 2), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("outer_left")}),
    ((2, 2, 3), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("east"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((2, 2, 4), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((2, 2, 5), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((2, 2, 6), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((2, 2, 7), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("east"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((2, 2, 8), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("east"), 'half': StringTag("bottom"), 'shape': StringTag("outer_left")}),
    ((2, 7, 3), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("east"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((2, 7, 7), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("east"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((3, 0, 0), "universal_minecraft:dirt", {}),
    ((3, 0, 1), "universal_minecraft:dirt", {}),
    ((3, 0, 2), "universal_minecraft:dirt", {}),
    ((3, 0, 3), "universal_minecraft:dirt", {}),
    ((3, 0, 4), "universal_minecraft:dirt", {}),
    ((3, 0, 5), "universal_minecraft:dirt", {}),
    ((3, 0, 6), "universal_minecraft:dirt", {}),
    ((3, 0, 7), "universal_minecraft:dirt", {}),
    ((3, 0, 8), "universal_minecraft:dirt", {}),
    ((3, 0, 9), "universal_minecraft:dirt", {}),
    ((3, 0, 10), "universal_minecraft:dirt", {}),
    ((3, 1, 0), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((3, 1, 1), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((3, 1, 2), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((3, 1, 3), "universal_minecraft:dirt", {}),
    ((3, 1, 4), "universal_minecraft:dirt", {}),
    ((3, 1, 5), "universal_minecraft:dirt", {}),
    ((3, 1, 6), "universal_minecraft:dirt", {}),
    ((3, 1, 7), "universal_minecraft:dirt", {}),
    ((3, 1, 8), "universal_minecraft:dirt", {}),
    ((3, 1, 9), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((3, 1, 10), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((3, 2, 2), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((3, 2, 3), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((3, 2, 4), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((3, 2, 5), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((3, 2, 6), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((3, 2, 7), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((3, 2, 8), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((3, 3, 3), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((3, 3, 7), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((3, 4, 3), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((3, 4, 7), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((3, 5, 3), "universal_minecraft:wall", {'material': StringTag("cobblestone"), 'east': StringTag("none"), 'north': StringTag("none"), 'south': StringTag("none"), 'up': StringTag("true"), 'west': StringTag("none")}),
    ((3, 5, 7), "universal_minecraft:wall", {'material': StringTag("cobblestone"), 'east': StringTag("none"), 'north': StringTag("none"), 'south': StringTag("none"), 'up': StringTag("true"), 'west': StringTag("none")}),
    ((3, 6, 3), "universal_minecraft:stone_bricks", {'variant': StringTag("chiseled")}),
    ((3, 6, 7), "universal_minecraft:stone_bricks", {'variant': StringTag("chiseled")}),
    ((3, 7, 2), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("south"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((3, 7, 3), "universal_minecraft:slab", {'material': StringTag("stone_brick"), 'type': StringTag("bottom")}),
    ((3, 7, 7), "universal_minecraft:slab", {'material': StringTag("stone_brick"), 'type': StringTag("bottom")}),
    ((3, 7, 8), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("north"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((4, 0, 0), "universal_minecraft:dirt", {}),
    ((4, 0, 1), "universal_minecraft:dirt", {}),
    ((4, 0, 2), "universal_minecraft:dirt", {}),
    ((4, 0, 3), "universal_minecraft:dirt", {}),
    ((4, 0, 4), "universal_minecraft:dirt", {}),
    ((4, 0, 5), "universal_minecraft:dirt", {}),
    ((4, 0, 6), "universal_minecraft:dirt", {}),
    ((4, 0, 7), "universal_minecraft:dirt", {}),
    ((4, 0, 8), "universal_minecraft:dirt", {}),
    ((4, 0, 9), "universal_minecraft:dirt", {}),
    ((4, 0, 10), "universal_minecraft:dirt", {}),
    ((4, 1, 0), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((4, 1, 1), "universal_minecraft:dirt", {}),
    ((4, 1, 2), "universal_minecraft:dirt", {}),
    ((4, 1, 3), "universal_minecraft:dirt", {}),
    ((4, 1, 4), "universal_minecraft:dirt", {}),
    ((4, 1, 5), "universal_minecraft:dirt", {}),
    ((4, 1, 6), "universal_minecraft:dirt", {}),
    ((4, 1, 7), "universal_minecraft:dirt", {}),
    ((4, 1, 8), "universal_minecraft:dirt", {}),
    ((4, 1, 9), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((4, 1, 10), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((4, 2, 1), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("east"), 'half': StringTag("bottom"), 'shape': StringTag("outer_right")}),
    ((4, 2, 2), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((4, 2, 3), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((4, 2, 4), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((4, 2, 5), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((4, 2, 6), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((4, 2, 7), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((4, 2, 8), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((4, 2, 9), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("east"), 'half': StringTag("bottom"), 'shape': StringTag("outer_left")}),
    ((4, 3, 4), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("outer_left")}),
    ((4, 3, 5), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("east"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((4, 3, 6), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("outer_right")}),
    ((5, 0, 0), "universal_minecraft:dirt", {}),
    ((5, 0, 1), "universal_minecraft:dirt", {}),
    ((5, 0, 2), "universal_minecraft:dirt", {}),
    ((5, 0, 3), "universal_minecraft:dirt", {}),
    ((5, 0, 4), "universal_minecraft:dirt", {}),
    ((5, 0, 5), "universal_minecraft:dirt", {}),
    ((5, 0, 6), "universal_minecraft:dirt", {}),
    ((5, 0, 7), "universal_minecraft:dirt", {}),
    ((5, 0, 8), "universal_minecraft:dirt", {}),
    ((5, 0, 9), "universal_minecraft:dirt", {}),
    ((5, 0, 10), "universal_minecraft:dirt", {}),
    ((5, 1, 0), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((5, 1, 1), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((5, 1, 2), "universal_minecraft:dirt", {}),
    ((5, 1, 3), "universal_minecraft:dirt", {}),
    ((5, 1, 4), "universal_minecraft:dirt", {}),
    ((5, 1, 5), "universal_minecraft:dirt", {}),
    ((5, 1, 6), "universal_minecraft:dirt", {}),
    ((5, 1, 7), "universal_minecraft:dirt", {}),
    ((5, 1, 8), "universal_minecraft:dirt", {}),
    ((5, 1, 9), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((5, 1, 10), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((5, 2, 1), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((5, 2, 2), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((5, 2, 3), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((5, 2, 4), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((5, 2, 5), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((5, 2, 6), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((5, 2, 7), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((5, 2, 8), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((5, 2, 9), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((5, 3, 4), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((5, 3, 5), "universal_minecraft:netherrack", {}),
    ((5, 3, 6), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((5, 4, 5), "universal_minecraft:fire", {'age': StringTag("15"), 'east': StringTag("false"), 'north': StringTag("false"), 'south': StringTag("false"), 'up': StringTag("false"), 'west': StringTag("false")}),
    ((6, 0, 0), "universal_minecraft:dirt", {}),
    ((6, 0, 1), "universal_minecraft:dirt", {}),
    ((6, 0, 2), "universal_minecraft:dirt", {}),
    ((6, 0, 3), "universal_minecraft:dirt", {}),
    ((6, 0, 4), "universal_minecraft:dirt", {}),
    ((6, 0, 5), "universal_minecraft:dirt", {}),
    ((6, 0, 6), "universal_minecraft:dirt", {}),
    ((6, 0, 7), "universal_minecraft:dirt", {}),
    ((6, 0, 8), "universal_minecraft:dirt", {}),
    ((6, 0, 9), "universal_minecraft:dirt", {}),
    ((6, 0, 10), "universal_minecraft:dirt", {}),
    ((6, 1, 0), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((6, 1, 1), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((6, 1, 2), "universal_minecraft:dirt", {}),
    ((6, 1, 3), "universal_minecraft:dirt", {}),
    ((6, 1, 4), "universal_minecraft:dirt", {}),
    ((6, 1, 5), "universal_minecraft:dirt", {}),
    ((6, 1, 6), "universal_minecraft:dirt", {}),
    ((6, 1, 7), "universal_minecraft:dirt", {}),
    ((6, 1, 8), "universal_minecraft:dirt", {}),
    ((6, 1, 9), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((6, 1, 10), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((6, 2, 1), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("west"), 'half': StringTag("bottom"), 'shape': StringTag("outer_left")}),
    ((6, 2, 2), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((6, 2, 3), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((6, 2, 4), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((6, 2, 5), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((6, 2, 6), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((6, 2, 7), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((6, 2, 8), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((6, 2, 9), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("west"), 'half': StringTag("bottom"), 'shape': StringTag("outer_right")}),
    ((6, 3, 4), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("west"), 'half': StringTag("bottom"), 'shape': StringTag("outer_left")}),
    ((6, 3, 5), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("west"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((6, 3, 6), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("west"), 'half': StringTag("bottom"), 'shape': StringTag("outer_right")}),
    ((7, 0, 0), "universal_minecraft:dirt", {}),
    ((7, 0, 1), "universal_minecraft:dirt", {}),
    ((7, 0, 2), "universal_minecraft:dirt", {}),
    ((7, 0, 3), "universal_minecraft:dirt", {}),
    ((7, 0, 4), "universal_minecraft:dirt", {}),
    ((7, 0, 5), "universal_minecraft:dirt", {}),
    ((7, 0, 6), "universal_minecraft:dirt", {}),
    ((7, 0, 7), "universal_minecraft:dirt", {}),
    ((7, 0, 8), "universal_minecraft:dirt", {}),
    ((7, 0, 9), "universal_minecraft:dirt", {}),
    ((7, 0, 10), "universal_minecraft:dirt", {}),
    ((7, 1, 0), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((7, 1, 1), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((7, 1, 2), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((7, 1, 3), "universal_minecraft:dirt", {}),
    ((7, 1, 4), "universal_minecraft:dirt", {}),
    ((7, 1, 5), "universal_minecraft:dirt", {}),
    ((7, 1, 6), "universal_minecraft:dirt", {}),
    ((7, 1, 7), "universal_minecraft:dirt", {}),
    ((7, 1, 8), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((7, 1, 9), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((7, 1, 10), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((7, 2, 2), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((7, 2, 3), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((7, 2, 4), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((7, 2, 5), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((7, 2, 6), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((7, 2, 7), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((7, 2, 8), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((7, 3, 3), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((7, 3, 7), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((7, 4, 3), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((7, 4, 7), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((7, 5, 3), "universal_minecraft:wall", {'material': StringTag("cobblestone"), 'east': StringTag("none"), 'north': StringTag("none"), 'south': StringTag("none"), 'up': StringTag("true"), 'west': StringTag("none")}),
    ((7, 5, 7), "universal_minecraft:wall", {'material': StringTag("cobblestone"), 'east': StringTag("none"), 'north': StringTag("none"), 'south': StringTag("none"), 'up': StringTag("true"), 'west': StringTag("none")}),
    ((7, 6, 3), "universal_minecraft:stone_bricks", {'variant': StringTag("chiseled")}),
    ((7, 6, 7), "universal_minecraft:stone_bricks", {'variant': StringTag("chiseled")}),
    ((7, 7, 2), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("south"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((7, 7, 3), "universal_minecraft:slab", {'material': StringTag("stone_brick"), 'type': StringTag("bottom")}),
    ((7, 7, 7), "universal_minecraft:slab", {'material': StringTag("stone_brick"), 'type': StringTag("bottom")}),
    ((7, 7, 8), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("north"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((8, 0, 0), "universal_minecraft:dirt", {}),
    ((8, 0, 1), "universal_minecraft:dirt", {}),
    ((8, 0, 2), "universal_minecraft:dirt", {}),
    ((8, 0, 3), "universal_minecraft:dirt", {}),
    ((8, 0, 4), "universal_minecraft:dirt", {}),
    ((8, 0, 5), "universal_minecraft:dirt", {}),
    ((8, 0, 6), "universal_minecraft:dirt", {}),
    ((8, 0, 7), "universal_minecraft:dirt", {}),
    ((8, 0, 8), "universal_minecraft:dirt", {}),
    ((8, 0, 9), "universal_minecraft:dirt", {}),
    ((8, 0, 10), "universal_minecraft:dirt", {}),
    ((8, 1, 0), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((8, 1, 1), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((8, 1, 2), "universal_minecraft:dirt", {}),
    ((8, 1, 3), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((8, 1, 4), "universal_minecraft:dirt", {}),
    ((8, 1, 5), "universal_minecraft:dirt", {}),
    ((8, 1, 6), "universal_minecraft:dirt", {}),
    ((8, 1, 7), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((8, 1, 8), "universal_minecraft:dirt", {}),
    ((8, 1, 9), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((8, 1, 10), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((8, 2, 2), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("outer_right")}),
    ((8, 2, 3), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("west"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((8, 2, 4), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((8, 2, 5), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((8, 2, 6), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((8, 2, 7), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("west"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((8, 2, 8), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("west"), 'half': StringTag("bottom"), 'shape': StringTag("outer_right")}),
    ((8, 7, 3), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("west"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((8, 7, 7), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("west"), 'half': StringTag("top"), 'shape': StringTag("straight")}),
    ((9, 0, 0), "universal_minecraft:dirt", {}),
    ((9, 0, 1), "universal_minecraft:dirt", {}),
    ((9, 0, 2), "universal_minecraft:dirt", {}),
    ((9, 0, 3), "universal_minecraft:dirt", {}),
    ((9, 0, 4), "universal_minecraft:dirt", {}),
    ((9, 0, 5), "universal_minecraft:dirt", {}),
    ((9, 0, 6), "universal_minecraft:dirt", {}),
    ((9, 0, 7), "universal_minecraft:dirt", {}),
    ((9, 0, 8), "universal_minecraft:dirt", {}),
    ((9, 0, 9), "universal_minecraft:dirt", {}),
    ((9, 0, 10), "universal_minecraft:dirt", {}),
    ((9, 1, 0), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((9, 1, 1), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((9, 1, 2), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((9, 1, 3), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((9, 1, 4), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((9, 1, 5), "universal_minecraft:dirt", {}),
    ((9, 1, 6), "universal_minecraft:dirt", {}),
    ((9, 1, 7), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((9, 1, 8), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((9, 1, 9), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((9, 1, 10), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((9, 2, 4), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("south"), 'half': StringTag("bottom"), 'shape': StringTag("outer_right")}),
    ((9, 2, 5), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("west"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((9, 2, 6), "universal_minecraft:stairs", {'material': StringTag("stone_brick"), 'facing': StringTag("north"), 'half': StringTag("bottom"), 'shape': StringTag("outer_left")}),
    ((10, 0, 0), "universal_minecraft:dirt", {}),
    ((10, 0, 1), "universal_minecraft:dirt", {}),
    ((10, 0, 2), "universal_minecraft:dirt", {}),
    ((10, 0, 3), "universal_minecraft:dirt", {}),
    ((10, 0, 4), "universal_minecraft:dirt", {}),
    ((10, 0, 5), "universal_minecraft:dirt", {}),
    ((10, 0, 6), "universal_minecraft:dirt", {}),
    ((10, 0, 7), "universal_minecraft:dirt", {}),
    ((10, 0, 8), "universal_minecraft:dirt", {}),
    ((10, 0, 9), "universal_minecraft:dirt", {}),
    ((10, 0, 10), "universal_minecraft:dirt", {}),
    ((10, 1, 0), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((10, 1, 1), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((10, 1, 2), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((10, 1, 3), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((10, 1, 4), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((10, 1, 5), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((10, 1, 6), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((10, 1, 7), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((10, 1, 8), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((10, 1, 9), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
    ((10, 1, 10), "universal_minecraft:grass_block", {'snowy': StringTag("false")}),
]
