# Auto-generated building blueprint
NAME = "bp_006"
BLOCKS = [
    ((0, 0, 0), "universal_minecraft:dirt", {}),
    ((0, 1, 0), "universal_minecraft:dirt", {}),
    ((0, 2, 0), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((0, 3, 0), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((0, 4, 0), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((0, 5, 0), "universal_minecraft:log", {'material': StringTag("dark_oak"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((0, 6, 0), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((0, 7, 0), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((0, 8, 0), "universal_minecraft:log", {'material': StringTag("dark_oak"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((0, 9, 0), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((0, 10, 0), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((0, 11, 0), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("east"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
    ((1, 0, 0), "universal_minecraft:dirt", {}),
    ((1, 1, 0), "universal_minecraft:dirt", {}),
    ((1, 2, 0), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((1, 3, 0), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((1, 4, 0), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((1, 5, 0), "universal_minecraft:log", {'material': StringTag("dark_oak"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((1, 6, 0), "universal_minecraft:wall", {'material': StringTag("cobblestone"), 'east': StringTag("tall"), 'north': StringTag("none"), 'south': StringTag("none"), 'up': StringTag("false"), 'west': StringTag("tall")}),
    ((1, 7, 0), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((1, 8, 0), "universal_minecraft:log", {'material': StringTag("dark_oak"), 'axis': StringTag("y"), 'stripped': StringTag("false")}),
    ((1, 9, 0), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((1, 10, 0), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((1, 11, 0), "universal_minecraft:stone_bricks", {'variant': StringTag("normal")}),
    ((1, 12, 0), "universal_minecraft:stairs", {'material': StringTag("dark_oak"), 'facing': StringTag("east"), 'half': StringTag("bottom"), 'shape': StringTag("straight")}),
]
